.github/workflows/build.yml
.gitignore

Adds a basic CI and PR validation workflow, with builds initiated on PRs (to `master` branch) and VSIX packaging/archival initiated on commits (to `master` branch). Builds are performed across the three supported platforms to help catch platform-specific issues as well as to serve as a foundation for future unit/integration test execution.

Add basic CI workflow

---

package-lock.json
package.json
src/extension.ts
tsconfig.json

Following PR fixes the deprecated warning, screenshot below. in an attempt to fix this: https://github.com/Azure/vscode-aks-tools/issues/14 
* The `DOM` inclusion in `tsconfig` as build solution is detailed here: https://github.com/Azure/ms-rest-js/issues/367 
* I updated the `azure/arm-containerservice` to `@azure/arm-containerservice`  https://www.npmjs.com/package/@azure/arm-containerservice  more details here: https://github.com/Azure/azure-sdk-for-js/blob/master/documentation/Migration.md 
* But the key challenge I had to fix is this: (Which will explain my `<unknown>` type conversion.
so after change, I got the following error on `azcs.ContainerServiceClient(credentials, target.root.subscriptionId);`
Which probably has to do with the type which get passed as `target` so if I do any …

Fix arm-containerservice deprecated pacakages warning.

---

package-lock.json
package.json
src/extension.ts
tsconfig.json

This reverts commit 292e4b7f91a842a70c1bf27b7958f000f954d83c. (Which is the update of `@azure/containerservices`, we cannot update this package at the moment because we depend on various packages which underneath still on `ms-rest`.
**If anyone keen for details** (readers beside who are already known to issue) 
* Please refer our detail discussion here: https://github.com/Azure/vscode-aks-tools/issues/14#issuecomment-641612514 
Reverting this fixes our `merge + save kubeconfig functionality`
Thanks

Revert "Fix arm-containerservice deprecated pacakages warning. (#23)"

---

src/commands/detectorDiagnostics/helpers/networkconnectivityhtmlhelper.ts
src/commands/detectorDiagnostics/webviews/networkconnectivity/networkConnectivity.html

I noticed a behaviour that for a cluster once that app lens API was returning data but it was empty for a dataset `(I cannot replicate it, because it was one-off data glitch)`  for some fields and it started working on the second go, so this handle will help in guaranteeing that at least the HTML handling display.
* Added `.length` check to make sure actually the data exist for that index before, read any existing value.
* Added `handlebar` if statements to handle the `html` display` 
Adding them as pro-active checks.
Thanks,

Detector feature: Safe handling clunky embedded html responce from app lens api.

---

src/extension.ts

This PR is to fix `rbac related save-kubeconfig` issue: https://github.com/Azure/vscode-aks-tools/issues/4
Also seems like it is recommended to use `listClusterUserCredentials` instead of `getaccessprofiler` here https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/getaccessprofile 
Opening this as a draft for Ivan to take a quick look. Thanks.
cc: @itowlson

Fix for rbac save-kubeconfig by using ListClusterUserCredentials.

---

src/commands/periscope/periscope.ts
src/commands/utils/host.ts
src/extension.ts

Draft PR to get some thoughts on generalising the `telemetry` with the `registerCommand`. 
This work creates a helper for `registerCommand` + `EnableTelemetry` ==> `registerCommandWithTelemetry` and everytime user will run any feature under this extension telemetry data will also be part of it.
I have tested the following the changes locally and they appear the `VSCodeExt` db for telemetry. 
* Associated work item: https://github.com/Azure/vscode-aks-tools/issues/34 
Thanks heaps, cc: @itowlson 🙏😊

Telemetry wrapper for register command.

---

resources/webviews/periscope/periscope.html

* Fix the spelling of `Download` not `Downloade`. 
cc: @itowlson, thank you.

Fix download spelling.

---

src/commands/azureServiceOperators/ui/azureservicebrowser.ts

I found this last night when I was just playing around with this feature in extension, that `api-resources --api-group azure.microsoft.com --no-headers` always return `Empty` result, with `exit code == 0` when the ASO service is not installed. This can only be re-pro when you follow specific steps mentioned below.
**For example:** (I created new acs-cluster which has ASO not installed, and ran : kubectl for aspi-resource), this is what I get as result. Essentially when the resource is installed,  the kubectl will return something.
**Specific steps to repro in Extension** 
* Create new aks-cluster and then set it as current context.
* Now close the extension and re-open it, what will happen is that the `registerNode` function will trigger and hit this line of code where is `return` of …

Handle sceanrio when api-resource returns empty for all cluster without ASO installed.

---

README.md

This is to remove the build badge because gihutb has security issue regarding this: 
Some details about this issue here: 
* https://github.com/microsoft/vscode-vsce/issues/183 
* https://github.com/isaacs/github/issues/316 
* https://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown/16462143#16462143
Thanks heaps, @itowlson 🙏

Remove github build badge due to github SVG issue.

---

package-lock.json
package.json

This PR fixes the ubuntu `vice package` error, just involve updating of `azure-storage` package to the latest.
Screenshot of successful run in WSL. Thanks 🙏

update azure-storage package to fix npm vsce error.

---

package-lock.json
package.json
src/commands/periscope/helpers/periscopehelper.ts
src/commands/utils/azurestorage.ts

This PR is continuation for the dependency fix, but this is final of it, reason being left over packages which are showing as dependency alert for this repository is actually just the decency of `@azure/` packages which are new storage packages. 
Following changes moves this code base 100 % away from the use of deprecated `azure-storage` package and use `@azure/storage-xxx` packages. more detail here: https://github.com/Azure/azure-storage-node or https://www.npmjs.com/package/azure-storage 
I have smoke tested this locally, adding PR for a quick look for more experienced eyes.
Thank you so much. ❤️🙏☕️
fyi: with new `storage` API they have removed the `Const` hence the `string` values are used like they have reopened in their sample API.

Upgrade deprecated azure-storage package.

---

resources/yaml/aks-periscope.yaml

This PR fixes 2 things, 
* ~Firstly an ~ongoing issue~ (interesting thing is this validation is no-longer showing now so surely something to do with yaml validation triggered and silent now) within this extension and is happening with `aks-periscope` and just got bubbled around 24th Dec **more lengthy details** in periscope repo: https://github.com/Azure/aks-periscope/issues/141  - this validation was never happened before so surely something is changed which has probably bubbled the right error~.
* Secondly, This PR fixes the deprecation of `apiextensions.k8s.io/v1beta1` now moved to `v1`
* More details here: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122
Currently it is happening within the feature provided under this extension, hence …

Fix for periscope feature and update depricated api version from beta1 to v1.

---

README.md

Following PR enables the `vscode-marketplace` badges for the repo.
The new changes will add these 2 details, I learned about this via this repo: https://github.com/microsoft/vscode-js-debug 
It looks like this: 
**Extra:**
Also might be if anyone keen why the `build` badge won't work is because:
Some details about this issue here: 
* https://github.com/microsoft/vscode-vsce/issues/183 
* https://github.com/isaacs/github/issues/316 
* https://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown/16462143#16462143
Thank you so much in advance: ☕️🙏cc: @squillace, @itowlson,  @lstocchi  and @rzhang628 and wish you all happy New Years. ❤️🙏

Add ms marketplace version and ratings badge.

---

resources/yaml/aks-periscope.yaml

This PR fix deprecated message for deployment: `Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]` 
* https://kubernetes.io/docs/reference/labels-annotations-taints/#beta-kubernetes-io-os-deprecated 
Thanks,
cc: @peterbom

fix periscope deprecated beta tag.

---

.github/workflows/publish.yml

This PR fixes the body of the released-tag, which currently just contains the version, now it will contain the real changelog contents.
Thanks, cc: @peterbom , @rzhang628 - Thanks, 🙏❤️☕️

Fix the body of released note.

---

src/commands/utils/detectors.ts

Fix for vscode side of things slowness caused by internal server error in detector. Thank you @peterbom.
cc: @rzhang628 - now its quicker.
THanks!

remove retry policy for detector server error.

---

package-lock.json
package.json
resources/yaml/azure-kubernetes-service-helm.yml
resources/yaml/azure-kubernetes-service-kompose.yml
resources/yaml/azure-kubernetes-service-kustomize.yml
resources/yaml/azure-kubernetes-service.yml
src/commands/aksHelmStarterWorkflow/configureHelmStarterWorkflow.ts
src/commands/aksKomposeStarterWorkflow/configureKomposeStarterWorkflow.ts
src/commands/aksKustomizeStarterWorkflow/configureKustomizeStarterWorkflow.ts
src/commands/utils/configureWorkflowHelper.ts
src/extension.ts
src/tests/suite/deploystarterworkflow.test.ts

This PR enables all the leftover `AKS Starter workflow` to be pre-configured with `cluster-name and resource-name` for the user.
This PR enables: 
* Submenu for starter workflow.
* 3 new workflows are enabled aka, Helm, Compose, Customise.
Thanks heaps guys, @palma21, @qpetraroia , @rzhang628 , @gambtho & @peterbom ❤️☕️🙏 once approved we can plan a release next week.

Add leftover starter workflow for AKS.

---

.github/workflows/poll-starter-workflows.yml
src/commands/utils/configureWorkflowHelper.ts

This workflow runs every 6 hours (or on user dispatch) and will open a pull request if the starter workflows in this repo don't match the official ones. If a pull request is closed, this workflow will not open a PR for these specific changes again.
This allows this repo to be aware of workflow changes but have complete control over how / when they are merged in.
The configureWorkflowHelper.ts changes take advantage of our starter workflow's env variables and makes it so you don't have to manually insert brackets to every workflow. Note that this change breaks this repo until the poll starter workflows workflow executes and the resulting PR is merged in. This lets you see the workflow in action.
Overall, this change lets this project stay up-to-date with starter workflow changes easily and …

Add workflow to update starter workflows

---

.github/workflows/publish.yml

This PR fixes the empty `publish` field in release tag. 
The changelog was never getting read from changelog reader but from package reader hence it was empty. It is fixed now.
* Changes made according to this `underlying GH action` : https://github.com/mindsers/changelog-reader-action 
Thanks cc: @peterbom and @rzhang628 for review thanks guys! ❤️🙏☕️

Read changelog from right place.

---

src/commands/azureServiceOperators/ui/azureservicebrowser.ts

This fixes a warning that appears when loading the cluster hierarchy pane on Windows: `unable to match a printer suitable for the output format "'custom-columns=Name:.metadata.name'"`.
Because of the single quotes, this entire expression was being interpreted as an output format, when in fact the output format should just be 'custom-columns'.
Using the alternative syntax `-o custom-columns=...` is equally valid and appears to work.

Fix warning on Windows when loading clusters pane

---

package-lock.json
package.json
src/commands/aksNavToPortal/aksNavToPortal.ts
src/extension.ts

This PR enables the navigation to specific cluster issue, now user can `right-click` and choose `Show in Azure Portal` for their cluster and browser will be called for the portal to open the `cluster overview` page. I know this will make @peterbom really happy, as he shared the real use-case.
* **Use case:** Imagine you have too many clusters and it gets really hard if you are logging into the azure portal and your recent history has lost your cluster only way you could search is via search resource or navigating inside AKS in Azure portal, this way simplifies all this into just one-click and navigate to the AKS cluster azure portal page.
Thanks you so much guys! cc: @peterbom,  @gambtho and @rzhang628 + @qpetraroia ❤️🙏
**Working Screenshots:**

Enable navigation to azure portal feature.

---

package.json
src/commands/aksCreateClusterNavToAzurePortal/aksCreateClusterNavToAzurePortal.ts
src/commands/utils/clusters.ts
src/extension.ts

This PR enables the new `AKS Subscription` level command to open `create cluster from azure portal` screenshots below can show the real flow of screens.
This will help vscode audience to quickly create cluster transitioning from this extension to the portal.
Thank you and cc: @peterbom and @rzhang628 for reviews and eyeing this please. ❤️🙏☕️

Navigate to create AKS cluster portal.

---

package-lock.json
package.json
resources/webviews/aksclusterproperties/clusterproperties.html
resources/webviews/common/detector.css
src/azure-api-utils.ts
src/commands/aksBestPractices/aksBestPractices.ts
src/commands/aksCRUDDiagnostics/aksCRUDDiagnostics.ts
src/commands/aksClusterProperties/aksClusterProperties.ts
src/commands/aksCreateClusterNavToAzurePortal/aksCreateClusterNavToAzurePortal.ts
src/commands/aksIdentitySecurity/aksIdentitySecurity.ts
src/commands/aksKnownIssuesAvailabilityPerformance/aksKnownIssuesAvailabilityPerformance.ts
src/commands/aksNavToPortal/aksNavToPortal.ts
src/commands/aksNodeHealth/aksNodeHealth.ts
src/commands/aksStarterWorkflow/configureStarterWorkflow.ts
src/commands/azureServiceOperators/installAzureServiceOperator.ts
src/commands/networkAndConnectivityDiagnostics/networkAndConnectivityDiagnostics.ts
src/commands/periscope/helpers/periscopehelper.ts
src/commands/periscope/periscope.ts
src/commands/selectSubscriptions.ts
src/commands/utils/clusters.ts
src/commands/utils/detectors.ts
src/commands/utils/webviews.ts
src/extension.ts
src/tree/aksClusterTreeItem.ts
src/tree/azureAccountTreeItem.ts
src/tree/subscriptionTreeItem.ts
tsconfig.json
tslint.json
webpack.config.js

This needs revert because for some reason, the update of the `extension` package leads to bespoke VSIX broken, and needs investigation.
In debug mode it will work, and the hunch is that there is a tsconfig break which is causing it when the extension ui package is updated to latest.
https://github.com/Azure/vscode-aks-tools/pull/144
Thanks, cc: @peterbom

Revert extensionui update and start-stop feature.

---

package-lock.json
package.json
src/commands/periscope/helpers/periscopehelper.ts
src/commands/periscope/models/clusterFeatures.ts
src/commands/periscope/periscope.ts
src/commands/utils/azurestorage.ts
src/commands/utils/clusters.ts
src/commands/utils/text.ts

This updates the extension to use the latest version of Periscope (0.0.10) by default.
This version of Periscope has an optional Kustomize component, which should only be deployed if the cluster supports it. For this, there is some extra checking in the Periscope helper module to determine if this component is supported. Although there is just one feature/component right now, the code is structured such that the pattern can be extended to add further components later.
The `DIAGNOSTIC_RUN_ID` configuration value is required to support the new optional Periscope component, but may in future be required by the Periscope application.

Update latest Periscope version and support optional Windows features

---

.github/workflows/poll-starter-workflows.yml

There is a bug with the current polling mechanism, which goes roughly as follows:
1. A workflow run detects a change in the source templates. This updates both the 'seen' mapping (which then gets uploaded as an artifact), and the local workspace. It then creates a PR from the local changes. This is all working as intended.
2. The PR is not merged before the next run (maybe it's out of work hours or we're busy with something else).
3. The workflow runs again. This time, the 'seen' mapping contains the latest SHA hashes of the files and so no changes are made to the local workspace. It then creates/updates the PR, but because there are no changes [the PR is automatically closed](https://github.com/peter-evans/create-pull-request#action-behaviour).
What _should_ happen is that the PR is kept …

Poll Starter Workflow: Remove comparison between 'seen' and latest templates

---

src/commands/periscope/helpers/periscopehelper.ts

The release tag setting for Periscope allows any GH reference (branch, commit, tag), so this may not be a valid semver value.
Some logic for determining which components to deploy checks the version of Periscope being deployed using the release tag, which results in runtime errors when this is a branch or commit.
This changes that logic to use the image version, which is more likely to be a semver value (it still might not be, so we need to try and parse it first to avoid runtime errors).

Fix error when running Periscope using a branch release tag

---

package.json
src/commands/aksKubectlCommands/aksKubectlCommands.ts
src/extension.ts

This PR enables the `kubectl get events --all-namespaces` feature to enable user run quick commands using our helpful kubectl submenu.
Thanks heaps, @peterbom and @rzhang628 ❤️☕️🙏 fyi @gambtho

Kubectl get events feature.

---

CHANGELOG.md
package-lock.json
package.json

Publishing version `1.3.6` with web view css fix by using `asWebViewURI` api. Thanks heaps and cc: @peterbom and @rzhang628 + @gambtho ❤️🙏
Thanks,
^Tats

Changes for publishing 1.3.6

---

package-lock.json
package.json
src/commands/aksDeleteCluster/aksDeleteCluster.ts
src/commands/utils/clusters.ts
src/extension.ts

This PR is written to enable all the achievable `managed cluster operations` which we can integrate with users for `one-click` - `aks vscode` functionality. 
This PR adds the `submenu` along with one click `delete cluster` api trigger via the TS api: https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/delete?tabs=JavaScript 
🥷💡🙏 Please note: the api return void but it takes time, so I have added appropriate messaging for user to see what is happening. Also, to those who have so far used the `delete cluster operation` from portal have seen little-longer to delete the cluster which is the responsibility of API, hence you will see the `long running` beahviour via vscode as well.
💼☕️ Key advantage of this feature will be that not only in one-click user can delete the cluster but …

Enable delete cluster functionality.

---

package-lock.json
package.json
src/commands/aksRotateClusterCert/aksRotateClusterCert.ts
src/commands/utils/clusters.ts
src/extension.ts

This PR is written to piggy back on all the achievable `managed cluster operations` which we can integrate with users for `one-click` - `aks vscode` functionality. 
This PR adds the one click `rotate cluster certificate` api trigger via the TS api: https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/delete?tabs=JavaScript 
🥷💡🙏 Please note: the api return void but it takes time, so I have added appropriate messaging for user to see what is happening. Also, to those who have so far used the `rotate cluster certificate operation` from portal have seen little-longer to delete the cluster which is the responsibility of API, hence you will see the `long running` beahviour via vscode as well.
💼☕️ Key advantage of this feature will be that not only in one-click user can delete the …

Managed cluster rotate certificate feature.

---

resources/webviews/azureserviceoperator/azureserviceoperator.css
resources/webviews/periscope/periscope.css

I mistakenly [added some CSS padding to the wrong file](https://github.com/Azure/vscode-aks-tools/pull/181/files#diff-1b4ebc75fee5dcd8fb408864476596c83e3fb2ce6e49e11b20d261540e1249d5) when making the changes to support ASO for non-AKS clusters.
This moves it to the right place.

Move padding for ASO webview to correct css file

---

package.json
src/commands/aksKubectlCommands/aksKubectlCommands.ts
src/extension.ts

This PR enable quick access to the `Healthz, livez and readyz` k8s API endpoint health checks to the user.
More details for these are here: https://kubernetes.io/docs/reference/using-api/health-checks/ 
Thanks heaps, fyi and cc: @rzhang628 & @peterbom ☕️❤️💡🙏

Add k8s api healtch check submenu.

---

src/commands/aksKubectlCommands/aksKubectlCommands.ts

This avoids incorrect argument parsing on Windows.

Remove quotes around kubectl argument

---

package.json

This PR only updates the config to use the latest version released for Inspektor Gadget: [v0.12.1](https://github.com/inspektor-gadget/inspektor-gadget/releases/tag/v0.12.1).
cc @Tatsinnit

Update config to use kubectl-gadget v0.12.1

---

package.json
src/commands/aksInspektorGadget/aksInspektorGadget.ts
src/extension.ts

Thank you for taking time and reviewing this! This PR enables the few `Non-Interative` **inspector gadget command**. This PR capitalise the ground up work we did under #190
List of commands this drop enables are:
- Inspector gadget Top command
- TCP
- eBPF
- BlockIO
- File
- IG Snapshot
- Process
- Socket
- IG Profile
-  CPU
Sample:

Enable non-interactive Inspektor Gadget Commands.

---

src/commands/aksKubectlCommands/aksKubectlCommands.ts

I think we added this for testing purposes when enabling kubelogin for AAD clusters with local users disabled.
It's not needed because the common code for retrieving the kubeconfig takes care of this.

Remove unnecessary kubelogin download

---

package.json
src/commands/periscope/helpers/periscopehelper.ts

This accounts for a change in the way Periscope is deployed in the latest version. Because the image tag refers to a manifest containing images for each OS, the tag is now the same for both Linux and Windows deployments.

Update Periscope deployment to latest version

---

CHANGELOG.md
package-lock.json
package.json

Publishing version `1.3.12`, in this release we with add few updates as described below. Thanks heaps and cc: @peterbom and @rzhang628 ❤️🙏🎊🥷 + fyi @gambtho + @squillace 
Following feature are going out with this release:
* Remove unnecessary kubelogin download.
* Allow development of VS Code-themed webviews using UI toolkit and React framework.
* Update Periscope deployment to latest version.
* Remove deprecated activation events.
* Publish gh.io readme as a vscode documentation.
* Link the GH pages to the Readme doc of this repo.
Thanks heaps.

Publish 1.3.12.

---

package-lock.json
package.json
src/azure-api-utils.ts
src/commands/aksCreateCluster/aksCreateCluster.ts
src/commands/utils/clusters.ts
src/commands/utils/detectors.ts
src/tree/aksClusterTreeItem.ts
src/tree/subscriptionTreeItem.ts

This upgrades the `@azure/arm-resources` library to the latest version, which has support for creating a client with a specified ARM endpoint (as we do for the Container Services client).
This cleans up some client code because the newer libraries have better support for paged enumeration of resources. It also identified places where we were creating these clients directly rather than using our library function, so we are no always creating them in the same way.
The `clusters.ts` file is also cleaned up a little, so that the same functions can be called to create both `ResourceManagerClient` and `ContainerServicesClient` objects, without needing separate functions depending on whether you're starting from a subscription or a cluster.

Upgrade ARM resources library

---

package.json
src/commands/aksKubectlCommands/aksCustomiseKubectlCommand.ts
src/commands/aksKubectlCommands/aksKubectlCommands.ts
src/extension.ts

This is moving forward PR which is written with an intent to make part way progress on #222 
As part 1 - of this - the PR enables any user input kubectl command against their `aks` cluster. 
As a build up work, next we can do is to build a `kubectlfile.aks` file where user can add their list of `kubectl` commands and we can add a parser to hook so that we can read the input of that file and execute and record result for the user.
Current custom behaviour will look like this. 🙏☕️❤️ thank you so much as always.

Feature customise kubectl command

---

src/panels/BasePanel.ts
src/panels/DetectorPanel.ts
src/panels/PeriscopePanel.ts
src/tests/suite/webview.test.ts
src/webview-contract/messaging.ts
src/webview-contract/webviewTypes.ts
webview-ui/src/Periscope/Periscope.tsx
webview-ui/src/TestStyleViewer/TestStyleViewer.tsx
webview-ui/src/manualTest/periscopeTests.tsx
webview-ui/src/manualTest/testStyleViewerTests.tsx
webview-ui/src/utilities/manualTest.ts
webview-ui/src/utilities/vscode.ts

Addresses some shortcomings of the way messages between VSCode and Webviews were being defined:
- Individual messages had to be defined as their own types and then combined together into discriminated unions for each component (Periscope, detectors, etc.).
- Message types needed to be defined with a string `command` property matching the type name, which was error prone.
- When creating subscriptions to messages, it was possible to 'miss' message types by forgetting to add handlers for some types. This would result in a runtime error that could be hard to notice and debug.
These changes introduce a convention whereby all messages (in each direction) for a component are defined in a single type, avoiding the need to manually create discriminated unions. This message definition type looks …

Simplify definitions of messages and handlers for webviews

---

.vscode/tasks.json

This fixes the incorrectly configured pattern matching for the background task when debugging webviews. Specifically, it
- avoids the "task cannot be tracked, make sure to have a problem matcher defined" message
- avoids opening non-existent files from the VS Code 'problems' pane (caused by interpreting the file in the task's output as a relative path, when it's actually an absolute one).
- refreshes errors when changes are saved (previously it stopped monitoring after launching the watch task).

Fix problem matcher for webview debugging task

---

src/commands/utils/detectors.ts
src/panels/BasePanel.ts
src/panels/DetectorPanel.ts
src/panels/PeriscopePanel.ts
src/tests/suite/webview.test.ts
src/webview-contract/README.md
src/webview-contract/webviewDefinitions/detector.ts
src/webview-contract/webviewDefinitions/periscope.ts
src/webview-contract/webviewDefinitions/testStyleViewer.ts
src/webview-contract/webviewTypes.ts
webview-ui/src/Detector/Detector.tsx
webview-ui/src/Detector/SingleDetector.tsx
webview-ui/src/Detector/renderers/InsightsRenderer.tsx
webview-ui/src/Detector/renderers/MarkdownRenderer.tsx
webview-ui/src/Detector/utils.ts
webview-ui/src/Periscope/ErrorView.tsx
webview-ui/src/Periscope/NodeLogs.tsx
webview-ui/src/Periscope/Periscope.tsx
webview-ui/src/Periscope/SuccessView.tsx
webview-ui/src/TestStyleViewer/TestStyleViewer.tsx
webview-ui/src/main.tsx
webview-ui/src/manualTest/detectorTests.tsx
webview-ui/src/manualTest/main.tsx
webview-ui/src/manualTest/periscopeTests.tsx
webview-ui/src/manualTest/testStyleViewerTests.tsx

This introduces a combined type definition for all the webviews and associated identifiers. This allows the complete set of webviews to be known at compile time, meaning code that handles _all_ webviews can be type-checked to ensure that none have been missed, making the addition of new webviews less error-prone.
Because all types for a Webview can be determined from its content ID, generic type parameters are much shorter, e.g.:
```typescript
class DetectorPanel extends BasePanel<DetectorTypes.InitialState, DetectorTypes.ToWebViewMsgDef, DetectorTypes.ToVsCodeMsgDef>
```
is now
```typescript
class DetectorPanel extends BasePanel<"detector">
```
The `"detector"` string in the above example is also type-checked to allow intellisense and prevent mis-spelling.
The shared types (between VS …

Reorganize type structure of webview definitions

---

src/panels/BasePanel.ts

Courtesy of @hsubramanianaks: this avoids webviews losing their state when they are hidden.
See: https://code.visualstudio.com/api/extension-guides/webview#retaincontextwhenhidden
The next step will be to work on an alternative approach to address the documented concern that "this has high memory overhead and should only be used when other persistence techniques will not work".

Add state management to webviews

---

package-lock.json
package.json
src/commands/aksAbortLastOperation/aksAbortLastOperation.ts
src/commands/utils/clusters.ts
src/extension.ts

This PR enables the quick to `Abort Last Operation` managed cluster API via Vscode, bringing user experience feature closer to their favourite editor.
https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/abort-latest-operation?tabs=HTTP
Than you so much, fyi @peterbom, @gambtho, @hsubramanianaks  and @qpetraroia 
how it will work et. al. very handy command and as an upgrade in next drop we can integrate this in the `ClusterProperty` page.

Abort last operation on cluster.

---

src/panels/CreateClusterPanel.ts

This PR fixes the ripple effect of updating `"@azure/arm-containerservice": "^19.3.0",` from `17.*` which changed the way status is passed. hence there was a build failure on create cluster.
FYi and cc: @peterbom, thanks heaps.
https://learn.microsoft.com/en-us/javascript/api/%40azure/arm-containerservice/managedcluster?view=azure-node-latest

fix build.

---

webview-ui/src/Kubectl/Kubectl.module.css
webview-ui/src/manualTest/kubectlTests.tsx

Fixes a display issue where wide output of a `kubectl` command would increase the width of containing elements, which could push the 'Run' button out of the visible area of the screen.
This ensures that the `pre` element containing the output remains at the size dictated by its parent containers, and handles any scrolling itself.

Avoid lengthy kubectl output changing the layout of containing elements

---

src/commands/utils/azureAccount.ts

Fixes a bug introduced by my earlier refactoring.
The `isObject` function checks the argument's constructor name is equal to 'object'. In the case of errors, that's generally incorrect, because errors have been created with other constructors, like `new RestError(...)`.
This changes the error check to in `azureAccount.ts` to avoid using `isObject`.
Also searched the codebase for other incorrect usages, but there weren't any.

Remove incorrect use of isObject

---

package-lock.json
package.json

This reverts commit 00ea0eb9815a0c7689d3f2f0416a9da841ffceb3.
Fixes this @peterbom ☕️🎊
* Commit updated the vscode telemetry as the transitive dependency which does not support AIF keys.

Revert "Bump @microsoft/vscode-azext-utils from 2.1.3 to 2.1.4 (#367)"

---

src/commands/aksCreateCluster/aksCreateCluster.ts
src/commands/aksNavToPortal/aksNavToPortal.ts
src/commands/detectors/detectors.ts
src/commands/utils/detectors.ts
src/commands/utils/env.ts
src/panels/CreateClusterPanel.ts
src/panels/DetectorPanel.ts
src/webview-contract/webviewDefinitions/createCluster.ts
src/webview-contract/webviewDefinitions/detector.ts
webview-ui/src/CreateCluster/CreateCluster.tsx
webview-ui/src/CreateCluster/Success.tsx
webview-ui/src/CreateCluster/helpers/state.ts
webview-ui/src/Detector/Detector.tsx
webview-ui/src/Detector/state.ts
webview-ui/src/manualTest/createClusterTests.tsx
webview-ui/src/manualTest/detectorTests.tsx

We have a lot of duplicate code for generating URLs representing Azure resources in the Portal. There is some complexity to this, around ensuring we use the appropriate domain name for the user's cloud, and setting the correct query strings for identifying the referrer.
This moves that logic into a single function, which I thought would be really useful for #335.
**EDIT**: This has now been rebased on top of `main` after merging #335. It also includes a small change to display a link to the Portal for the deployment while the cluster creation is in progress.
~~Unfortunately, this had a far larger blast radius than I anticipated. Even more unfortunately, it conflicts heavily with #335 which is otherwise almost ready to merge.~~
~~So, I'm opening this as a draft to make clear the _kind_ of …

Move portal URL generation into a common function

---

src/panels/TcpDumpPanel.ts
src/webview-contract/webviewDefinitions/tcpDump.ts
webview-ui/src/TCPDump/CaptureFilters.tsx
webview-ui/src/TCPDump/TcpDump.module.css
webview-ui/src/TCPDump/TcpDump.tsx
webview-ui/src/TCPDump/filterScenarios/SpecificPodFilters.tsx
webview-ui/src/TCPDump/filterScenarios/TwoPodsFilters.tsx
webview-ui/src/TCPDump/protocols.ts
webview-ui/src/TCPDump/state.ts
webview-ui/src/TCPDump/state/captureNodeUpdate.ts
webview-ui/src/TCPDump/state/dataLoading.ts
webview-ui/src/TCPDump/state/nodeReferenceDataUpdate.ts
webview-ui/src/TCPDump/state/referenceDataUpdate.ts
webview-ui/src/TCPDump/state/scenarioFiltersUpdate.ts
webview-ui/src/components/ResourceSelector.tsx
webview-ui/src/manualTest/tcpDumpTests.tsx
webview-ui/src/utilities/array.ts

Capture files can become huge very quickly. We need to allow users to filter output so that file sizes are manageable.
This is achieved with a new `Filters` option:
Users can filter on network interface, as well as build a [pcap filter string](https://www.tcpdump.org/manpages/pcap-filter.7.html) using protocol/port fields, or editing it manually:
The number of options here could grow quite large and become mutually inconsistent, depending on which capture scenarios we want to support in future. For example, collecting outgoing traffic from a _single_ pod requires different filter options from traffic _between_ two known pods. Conceivably we might want to support other scenarios in the future, perhaps involving services or ingresses.
For this reason, we have also added a `Capture Scenario` …

Add filters for TCPDump

---

.vscode/launch.json
.vscode/tasks.json

I have been getting occasional errors launching debug profiles, that I can't reproduce reliably.
The error was `could not find the task "npm: webpack"`. Searching for that error, I found several _similar_ sounding problems, like [this](https://github.com/microsoft/vscode/issues/147193), but in all the examples I could see, the `preLaunchTask` value referred to an entry in `tasks.json`, which appears to be the recommended way to do it.
Creating this PR because making the change myself appeared to fix the issue I was getting, and it seems to be the "right" approach.

Fix occasional error message that npm is missing

---

src/panels/AzureServiceOperatorPanel.ts
src/panels/BasePanel.ts
src/panels/ClusterPropertiesPanel.ts
src/panels/CreateClusterPanel.ts
src/panels/DetectorPanel.ts
src/panels/InspektorGadgetPanel.ts
src/panels/KubectlPanel.ts
src/panels/PeriscopePanel.ts
src/panels/TcpDumpPanel.ts
src/tests/suite/webview.test.ts
src/webview-contract/messaging.ts
src/webview-contract/webviewTypes.ts

Addresses #376 
~~We need further discussion about how best to structure the properties that we emit: @Tatsinnit, @qpetraroia, @hsubramanianaks so opening this as draft for now.~~
Some background:
- Commands from webviews are invoked by sending a message from the webview to VS Code.
- These messages are well-known and explicitly defined for each webview. For example, the `createCluster` webview uses three messages:
- `getResourceGroupsRequest`
- `getLocationsRequest`
- `createClusterRequest`
- We probably **don't** want to emit telemetry for all of these events. In the above case we'd probably want an event for `createClusterRequest` only.
- We have some messages where the name itself is probably not sufficiently granular, and we'd need to extract some content from the message in order …

Support telemetry for commands from webviews

---

package-lock.json
package.json

We previously had to revert this in #374 because it depended on a newer telemetry library. Now we've updated our telemetry library, we can make this change.

Update vscode-azext-utils package

---

.vscode/launch.json
.vscode/tasks.json
package.json

Previously the `Extension` debug profile in `launch.json` ran all the production compilation and packaging steps for the `webview-ui` project and the main extension, _before_ launching a new VS Code window to execute the code being debugged. After making code changes, you would need to stop debugging and run the entire build over again.
This change runs webpack in `watch` mode when launching the `Extension` task, without pre-building the `webview-ui` project. This allows for much faster startup, and also means that the debugging session no longer needs to be stopped and restarted whenever a code change is saved (although the window still needs to be reloaded).
This is a trade-off. The drawback is that it's now the developer's responsibility to ensure the `webview-ui` project gets built …

Improve startup and refresh time for debugging extension

---

.vscode/tasks.json
webview-ui/.eslintrc.cjs

Our problem matcher was previously duplicating much of the definition for the [`$tsc-watch` problem matcher](https://github.com/microsoft/vscode/blob/860d67064a9c1ef8ce0c8de35a78bea01033f76c/extensions/typescript-language-features/package.json#L1614-L1632).
This instead re-uses the common problem matcher, but overrides some settings (file location, and begin/end regexes for watching changes that are different because of the way `tsc` is invoked from `vite`).
There was also a linting error in the `vite.config.ts` file referenced in a secondary `tsconfig` file (`tsconfig.node.json`), because eslint was not aware of this second typescript project file. The second change here ensures that `eslint` is aware of both.

Simplify webview dev task problem matcher

---

src/commands/aksClusterProperties/aksClusterProperties.ts
src/commands/aksCompareCluster/aksCompareCluster.ts
src/commands/aksCreateCluster/aksCreateCluster.ts
src/commands/aksCreateClusterNavToAzurePortal/aksCreateClusterNavToAzurePortal.ts
src/commands/aksDeleteCluster/aksDeleteCluster.ts
src/commands/aksNavToPortal/aksNavToPortal.ts
src/commands/aksReconcileCluster/aksReconcileCluster.ts
src/commands/aksRotateClusterCert/aksRotateClusterCert.ts
src/commands/aksStarterWorkflow/configureStarterWorkflow.ts
src/commands/detectors/detectors.ts
src/commands/periscope/helpers/periscopehelper.ts
src/commands/periscope/periscope.ts
src/commands/refreshSubscriptions.ts
src/commands/utils/azureAccount.ts
src/commands/utils/clusters.ts
src/commands/utils/detectors.ts
src/extension.ts
src/tree/aksClusterTreeItem.ts
src/tree/azureAccountTreeItem.ts
src/tree/subscriptionTreeItem.ts

We have three "tree item" implementation classes: `AzureAccountTreeItem`, `SubscriptionTreeItem` and `AksClusterTreeItem`.
These classes contain properties and functions that are specific to the VS Code treeview UI, including implementations for refreshing and loading child items that [the documentation says should not be called directly](https://github.com/Microsoft/vscode-azuretools/blob/main/utils/README.md#azure-extension-tree-data-provider). For this reason we should only be referring to these during the initial building of the Cloud Explorer treeview. For code invoked from commands we can instead use the corresponding interfaces: `SubscriptionTreeNode` and `AksClusterTreeNode`.
These changes made the `TreeItem` classes private (not `export`ed), and fixes consuming code to use the …

Make TreeItem implementation classes private

---

src/commands/aksCreateCluster/aksCreateCluster.ts
src/commands/aksDeleteCluster/aksDeleteCluster.ts
src/commands/utils/clusters.ts
src/panels/CreateClusterPanel.ts
src/tree/aksClusterTreeItem.ts
src/tree/subscriptionTreeItem.ts

Programmatically refresh the Cloud Explorer treeview after adding and deleting clusters.
This builds on the command to refresh the clusters under a subscription in the treeview (#393), and makes use of the slightly more constrained interface for interacting with TreeView items (#406).

Refresh subscriptions after adding and deleting clusters

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/website.yaml

These changes aer made in correlation with the following changes coming soon in the GH actions permissions. Please take a kind look. ❤️🙏☕️
* https://docs.opensource.microsoft.com/github/apps/permission-changes/
The latest CodeQl Already have these changes in place. https://github.com/Azure/vscode-aks-tools/blob/main/.github/workflows/codeql-analysis.yml#L27C1-L29C21
To start with going with the most safest option with read only permission. Given this will spread pretty soon lets try this out and I will gradually open similarity changes in other repos I know.
Thank you. ❤️🙏

Changes in correlation with new GH Action Permission Changes.

---

src/commands/aksCompareCluster/aksCompareCluster.ts
src/tree/aksClusterTreeItem.ts

This Pull Request intend to fix the issue #441 with `AZTreeItem` object which is working within the `azext-utils` given earlier we were supplying `ClusterName` only as the unique identity I think it was filtering that as the duplicated hence the failure during the TreeNode Creation.
Below is the **before** and **after** of this issue after the fix, I played around, and ~~will share the `vsix` for quick play around~~. Here is the link for the `vsix` to test if this fixes the issue for you. (Please rename file after download this `zip` file and then rename to `vsix` and then try to install it manually. 
Here are help how to install:
- [Helpful guidance how to install vsix manually](https://code.visualstudio.com/docs/editor/extension-marketplace#_manage-extensions) OR [guidance 2 how to …

Fix for making instance when cluster name is same but RG are different.

---

CHANGELOG.md
package-lock.json
package.json

Publishing version `1.4.1`, in this release we with add few key updates as described below. Thanks heaps @sprab for through testing in certain instances and cc: @sprab @peterbom and, @qpetraroia, @hsubramanianaks, ❤️🙏🎊🥷 fyi - @gambtho
Following fixes/feature/package updates will be going out with this release:
* Fix for making instance when cluster name is same but RG are different.
* Changes in correlation with new GH Action Permission Changes.
* Add badge for codeql and chai test fix.
* Add codeql analysis for repo.
* Add bestpractices progress and other badges.
* Dependabot updates.
Thanks heaps, for testing here is the vsix, (Please remove zip and the install in case anyone tests from here.)
[vscode-aks-tools-1.4.1-test copy.vsix.zip](https://github.com/Azure/vscode-aks-tools/files/140 …

Publish release 1.4.1

---

package-lock.json
package.json

This PR takes care of the intent being PR #480 , and as you can see builds are all green with this change in the PR because `vscode engine` needed upgrade as well. 🙏☕️
kind fyi and cc to @peterbom, @hsubramanianaks Thanks heaps.

Update types vscode version with engine.

---

.github/dependabot.yml

Should prevent build errors like [this](https://github.com/Azure/vscode-aks-tools/actions/runs/7879702255/job/21501142275?pr=483)

Group typescript-eslint dependencies together for Dependabot updates

---

src/commands/utils/download/download.ts

I missed calling the `WriteStream.end()` function in #567 - this is added here to ensure the stream is flushed and closed before the file is accessed.

Ensure file stream is closed after downloading

---

src/commands/utils/helper/kubectlGadgetDownload.ts

In the newer version of Inspektor Gadget which we're downloading, the archive file that gets downloaded contains a binary with a .exe extension on Windows (previously in v0.19.0 it had no extension). This caused the download/extract functionality to break.
This update recognises the newer archive structure.

Handle new archive structure for IG in windows

---

src/commands/aksAccount/aksAccount.ts
src/tree/azureAccountTreeItem.ts

Addresses #680 
This is just to fix the observed behaviour that:
1. The treeview can display a node saying 'select tenant' when in fact there's only one tenant to choose from; and
2. The 'select tenant' command currently doesn't do anything if there is only a single tenant to choose from.
There are some additional changes we can make to the session provider API that should make this kind of defect less likely. I'll address those in a separate issue and PR.

Fix treeview stuck with only 'select tenant' node

---

package.json
src/commands/draft/draftCommands.ts
src/commands/draft/types.ts
src/panels/draft/DraftDockerfilePanel.ts

This adds context menu items for the Draft commands, both in the file system explorer and the cloud explorer tree views:
It also marks the starter workflow commands as deprecated:

Add draft context menu commands and deprecate starter workflows

---

.github/workflows/restrict-pr-size.yml

This is moving forward PR, the size gate for PR for the repo is to regulate the bigger size PR for reasons mentioned here https://github.com/Azure/vscode-aks-tools/pull/708#issue-2326602863 
* This PR enable a special case: What this PR enables in the `commit` tag called `[skip pr-size]` which needs to be explicitly mentioned in the PR which will help in skipping the run for this pull request. 
* This will be for instances where PR cannot be broken at-all!! (Although it will be great to have a sanity check for the original writers to keep this in mind)
This is well tested against one of my repo for my fork.
Thanks heaps ☕️🙏❤️

Update/pr size workflow with skip tag for necessary need.

---

CHANGELOG.md
docs/book/src/README.md
docs/book/src/SUMMARY.md
docs/book/src/features/create-gh-workflow.md
package-lock.json
package.json

I'm proposing to release this before other features, so that we give as much notice as possible for the deprecation of the starter workflow commands.
Changes:
* Ensure initial selection values are populated in Draft.
* Add draft context menu commands and deprecate starter workflows.
* PR Size Check with skip tag.

Release 1.4.6

---

src/auth/azureSessionProvider.ts
src/auth/types.ts

Minimal changes for #682:
- add options for getting session
- don't require active token for selected tenant
This helps prevent issues like #680 from arising in the future. It also makes the `AzureSessionProvider` interface more resistant to breakages by adding an `Options` parameter for session retrieval options that might grow in the future (e.g. to enable specifying extra graph API scopes or application client IDs).
Design decisions:
1. We will make no immediate attempt to adhere to the structure proposed [here](https://github.com/microsoft/vscode-azuretools/pull/1722).
2. There is no implicit extra meaning to the `selectedTenant` property that assumes the user would be able to silently obtain a token for that tenant.
~~Opening as a draft since those decisions are debatable.~~
EDIT: I …

AzureSessionProvider changes

---

.github/workflows/restrict-pr-size.yml

This PR fixes: https://github.com/Azure/vscode-aks-tools/security/code-scanning/17
The pinning was missing to the hash.
Thanks heaps, and ❤️☕️🙏💡 cc: @qpetraroia , @hsubramanianaks , @sprab + @gambtho

Fix the code scanning.

---

CHANGELOG.md
package-lock.json
package.json

This PR is to release 1.4.7.
Please note: It will be nice if we get the #773 merge first and then this.
* Add developer-focused discussion of authentication and Draft work.
* Recategorize Draft commands as Automated Deployments.
* UX enhancements for Attach ACR to Cluster.
* Connect ACR to Cluster implementation.
* Avoid querying graph APIs for ASO.
* Add direct node-fetch dependency.
* Remove deprecated starter workflow commands.
* Remove starter workflow traces as its removed now. 
Thanks heaps all. thoughts et. al. cc: @qpetraroia , @hsubramanianaks , @sprab fyi @gambtho
Please do correct the description et. al. Thanks heaps.

Release for version 1.4.7

---

src/panels/draft/DraftDeploymentPanel.ts

Added flag "--skip-file-detection" 
The draft screen was freezing because it detected manifest files in the directory specified or child directories. By adding the "--skip-file-detection" to the draft command, we can remove the check on the draft side and rely on the extension to inform the user that manifest files are present.
Draft deployment screen was freezing as seen  [https://github.com/Azure/vscode-aks-tools/issues/786](here)

Adding flag to prevent draft from checking for manifests

---

src/commands/draft/draftCommands.ts

Previous github authentication token only provided access to publicly available repos., which prevented the extension from populating any private repos the user might have had.

Updated github auth scope to repo

---

package-lock.json
package.json
src/tree/azureAccountTreeItem.ts

This PR is aimed to fix #852 
Thanks heaps and can we please get a review and probable test for the vsix attached below. 
cc: @qpetraroia , @hsubramanianaks , @ReinierCC and @tejhan thanks heaps 🙏☕️
VSIX below: 
[vscode-aks-tools-1.4.8-auth-util-update-test.vsix.zip](https://github.com/user-attachments/files/16617640/vscode-aks-tools-1.4.8-auth-util-update-test.vsix.zip)

possible fix.

---

.github/workflows/build.yml

This PR fixes the github action for build with right syntax of node-version instead of version.

fix version to node-version

---

src/panels/TcpDumpPanel.ts
src/tests/suite/TcpDumpPanel.test.ts

To properly sanitize input strings we have to escape any special characters.
Wanted to get some feedback on this implementation, where I manually specified the special characters and are escaping.
Some other potential routes would be to use a library with this feature but, this would create a new dependency.
Currently have a simple test function in the same file. Can move this to a more appropriate location after feedback.

Escaping special regex chars

---

CHANGELOG.md
package-lock.json
package.json

This PR is for the release 1.4.9, please see the details below.
We need to wait for https://github.com/Azure/vscode-aks-tools/pull/888 to get merge and then we can send the vsix to quick test and release.
Parking this in a queue before we add more to this repo.
AKS diagnostic bug resolved & storage diagnostic added.
* Updated github auth scope to repo.
* Adding flag to prevent draft from checking for manifests.
* U/X add border for the row.
* Fix the eslint no-unused-vars errors.
* changing draft version to .38 and removing manual appname.
Thanks all.

Release to publish 1.4.9

---

webview-ui/src/ClusterProperties/ClusterProperties.module.css

This PR fixes a minor bug observed when scrolling through a cluster properties page. The information tooltip & icon are fixed & overlap with other content upon scrolling. This fixed behavior also caused the version chart to overflow vertically off of the page in some circumstances. (See video Below)
https://github.com/user-attachments/assets/ab49324f-b532-422b-a189-766fd3175714
https://github.com/user-attachments/assets/9b3e7b7f-fd77-4579-9769-8190056e9814
- Fixed tooltip issue & made slight changes to improve readability

Minor bug fix for cluster properties panel

---

src/extension.ts

This fix is purely for the aspect of things which leads to the fixing #930 Now once user select the aka **uncheck** `show welcome page` the walk thought will not show up.
because upon uncheck the property in workspace gets set like this, and we are making sure walkthrough is not called until that is set. Thank you so much @ReinierCC for testing and fyi/collab. <3 
* VSIX for testing: 
[vscode-aks-tools-1.4.9-fixwalkthrough.vsix.zip](https://github.com/user-attachments/files/17067610/vscode-aks-tools-1.4.9-fixwalkthrough.vsix.zip)
* This one is proper zip file so unzip and then use the vsix under that to install.
[Uploading vscode-aks-tools-1.4.9-fixwalkthrough.vsix.zip…]()

Fix for walkthrough and show welcome dependency.

---

src/panels/draft/DraftDockerfilePanel.ts

This PR is to fix the following issue:
where the "Automated Deployments: Draft a Dockerfile" page would freeze for any user input after clicking the create button.
This occured because the draft command being executed to create the dockerfile was waiting for cli style user input about the BUILDVERSION.
Previously the builderImageTag was or'ed with an empty string. But builderImageTag was already of type string | null .
By removing the empty string, the draft binary uses BUILDERTAG as null and does not request user input.
There still exists issue #944 for python dockerfiles. But the fix for that would best come from a modification to the draft binary itself.

Fixing freezing dockerfile create page 

---

src/commands/utils/env.ts
src/panels/CreateClusterPanel.ts
src/panels/templates/AutomaticCreateCluster.json
src/panels/utilities/ClusterSpecCreationBuilder.ts

This PR address two issues 
1. enhances the automatic sku preset cluster creation with Azure Kubernetes Service RBAC Cluster Admin role assigned to the user whoever creates the cluster. 
2. fixes the deployment url same to portal deploment blades

role assignments for automatic sku

---

src/panels/CreateClusterPanel.ts

This PR fixes when vscode authentication api returns tenantId and servicePrincipal in different formats.

fix for different format of serviceprincal id from auth sessions

---

webview-ui/src/Kubectl/Kubectl.module.css

This PR is just to add padding to save dialog in kubectl panel to add some spacing.

Kubectl savedialog UX changes

---

package.json
src/auth/azureSessionProvider.ts
src/auth/types.ts
src/commands/aksCreateCluster/aksCreateCluster.ts
src/commands/aksCreateCluster/aksCreateClusterFromCopilot.ts
src/commands/aksDeployManifest/aksDeployManifest.ts
src/commands/aksOpenKubectlPanel/aksOpenKubectlPanel.ts
src/panels/CreateClusterPanel.ts
src/panels/KubectlPanel.ts
src/plugins/kubectlGeneration/aksDocsRag/client.ts
src/plugins/kubectlGeneration/aksDocsRag/constants.ts
src/plugins/shared/clusterOptions/options/selectExistingClusterOption.ts
src/plugins/shared/clusterOptions/selectClusterOptions.ts
src/plugins/shared/pluginResponses.ts
src/plugins/shared/telemetry/logger.ts
src/plugins/shared/types.ts

This PR makes improvements to GHCP handlers UX:
- Fixes the jsonpath escape quotes for the kubectl command invocation.
- Deployment of manifest success link is now routed to workloads page in Azure portal.
- Adds EU boundary header for RAG client. This is ensures compliance with EUDP. 
- Maintain list of EU regions as stated in azure docs (link in commented code)  
- Adds useful telemetry for the handlers. --- No PII or user data are getting logged, only actions/commands.
- Improve plugin responses:
- Kubectl command generation handler:  
- Create AKS cluster handler:

Improvements for GH copilot handlers

---

.github/workflows/publish-v2.yml

Removing npm webpack and replacing with npx publish.
The 'vsce package' operation calls 'npm webpack' as well build the required .vsix file for production.
Tested operation on github runner. vsix file present in directroy, and '*.vsix' was able to pick up the file.

New Publish Workflow Fix

---

docs/book/src/README.md
docs/book/src/SUMMARY.md
package.json
src/commands/aksKaito/akskaitoGenerateYaml.ts
src/panels/KaitoPanel.ts
webview-ui/src/Kaito/Kaito.tsx

This PR fixes the typo of misrepresenting Kaito as word to KAITO as I guess (Kubernetes AI ToolChain Operation) 
fyi to all.

kaito needs to be KAITO named.

---

src/panels/KaitoPanel.ts
webview-ui/src/Kaito/Kaito.tsx

This PR fixes few leftover KAITO stuff, which we noticed, it made sense to merge the long running PR and whatever was left we cover in small one part of which was covered in previous #1022 and next part is the disable of the button so user cannot press install multiple times which lead to failure of too many operation.
Idea for the implementation is: 
- The `isDisabled` state is **initialized** as `false`.
- After clicking the button, `onClickKaitoInstall` is triggered, and the button is disabled by setting `**isDisabled**` to `true`.
- The `disabled` attribute on the button prevents further clicks once it's **disabled**.
Thanks heaps, and result is here:

Fix multiclick by disabling the button.

---

CHANGELOG.md
package-lock.json
package.json

This PR is for the release `1.5.0`, please see the details below.
* Kaito deployment & ux updates.
* New Publish Action on Secure Runner.
* Improvements for GH copilot handlers.
* New Publish Workflow Fix.
* Manually fetching package.json version.
* Changing npm to npx.
* Kaito additional error & quota handling.
* kaito needs to be KAITO named.
* Add documentation for GH Copilot handlers and telemetry.
Thank you so much to @tejhan, @ReinierCC, @kejatura-dev, @ivelisseca, @qpetraroia, @hsubramanianaks, Joy, Sachi for contributions, testing and reviews.
❤️ 
* Here is the vsix:  [vscode-aks-tools-1.4.11-buttondisabled-fixdoubelinfo.vsix.zip](https://github.com/user-attachments/files/17517118/vscode-aks-tools-1.4.11-buttondisabled-fixdoubelinfo.vsix.zip)
- …

Publish version 1.5.0

---

src/extension.ts

Thanks all in advance, this work is part of the multi pronged work which may be needed for the walkthrough scenarios, the key discussion reside here (specific to this implementation) : https://github.com/Azure/vscode-aks-tools/discussions/1050#discussioncomment-11185795 
In our activate function, compare the stored version with the current extension version. If they differ, show the walkthrough and update the stored version.
To display a VS Code walkthrough only once per version, we can use the extension's context to track whether the walkthrough has been shown for the current version. Here's how you can implement this:
1. **Version Check**: The code checks the current version of your extension using `packageJSON.version`.
2. **Stored Version**: It retrieves the last shown version from …

Track Version in the Extension Code, for walkthrough.

---

CHANGELOG.md
package-lock.json
package.json

This PR is for the release 1.5.2, please see the details below. Small release to testing new publishing pipeline.
* Engine and VSCE package update.
Thank you so much to @tejhan, @qpetraroia, @hsubramanianaks, @Tatsinnit for contributions, testing and reviews.
VSIX for testing (rename and remove '.zip'): [vscode-aks-tools-1.5.2-test.vsix.zip](https://github.com/user-attachments/files/17738979/vscode-aks-tools-1.5.2-test.vsix.zip)

Publish release 1.5.2

---

package.json

The newest version of Inspektor Gadget was released yesterday: https://github.com/inspektor-gadget/inspektor-gadget/releases/tag/v0.34.0
This PR updates the `kubectl-gadget` binary to be pulled from the latest release `v0.34.0`

kubectl-gadget: Update to v0.34.0

---

src/commands/utils/acrs.ts
src/commands/utils/graph.ts
src/commands/utils/roleAssignments.ts

Redo of previous [PR](https://github.com/Azure/vscode-aks-tools/pull/1071) due to signing issues.
This PR adds the main utility functions that will be required for the new automated deployments experience.
Utility Files Accomplish the Following:
ACR Creation/Manipulation
Application Registration Creation
Federated Credential Creation
Role Assignments for clusters and ACR
Functionality was tested with playground file found here:[playground file](https://github.com/ReinierCC/vscode-aks-tools/blob/auto-deployments-utility/src/commands/devhub/connectGH.ts) (Not included in this PR)

Auto Deployments Utility Logic

---

webview-ui/package-lock.json
webview-ui/package.json
webview-ui/src/InspektorGadget/TraceOutput.tsx

Hiya, This PR fixes #1088 
[vscode-aks-tools-1.5.2-dependabot-fix.vsix.zip](https://github.com/user-attachments/files/17910482/vscode-aks-tools-1.5.2-dependabot-fix.vsix.zip)
I think the error `TS2322: Type '{ children: unknown[]; }' is not assignable to type '{ children?: ReactNode; }'` occurs because the `children` prop in JSX expects a type assignable to `ReactNode`, and in the code, the `children` prop contains `unknown[]`, which is incompatible.
This issue typically arises from returning `<>{value}</>` where `value` has the type `unknown`. To resolve the error, you need to ensure that the `value` is safely cast or transformed into a type compatible with `ReactNode` before being rendered.
- In cases where `value` is `unknown`, explicitly cast or transform it into a string using …

Fix the dependabot related issue.

---

CHANGELOG.md
package-lock.json
package.json

This PR is for the release `1.5.3`, please see the details below. For all folks to take a look and we can do the release early next week.
Please Note: Documentation of KAITO is taken care of in #1105 
* KAITO - Model Management & Chat Features.
* Auto Deployments Utility Logic.
* Remove activation event trigger.
* `kubectl-gadget`: Update to v0.34.0.
Thank you so much to @burak-ok, @ReinierCC, @tejhan, @qpetraroia, @hsubramanianaks, @Tatsinnit for contributions, testing and reviews.
❤️
VSIX for quick test for anyone keen. please: 
[vscode-aks-tools-1.5.3-test.vsix.zip](https://github.com/user-attachments/files/18028894/vscode-aks-tools-1.5.3-test.vsix.zip)

Publish release 1.5.3

---

src/panels/templates/DevTestCreateCluster.json

This PR fixes an issue where nodeOSUpgradeChannel was missing in the properties for AKS cluster creation ARM template causing CVE alerts. This has been set to NodeImage which updates NodeImage weekly - more details below 
https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-node-os-image?tabs=azure-cli#update-ownership-and-schedule
customers control these upgrades via maintenance configurations. More details here - https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-node-os-image?tabs=azure-cli#node-os-planned-maintenance-windows

add node os upgrade channel

---

CHANGELOG.md
package-lock.json
package.json

This PR is for the release `1.5.4`, please see the details below. For all folks to take a look and we can do the release early next week.
• Add node os upgrade channel.
• Adding refresh option to cluster properties page.
• Dependabot updates and bumps.
Thank you so much to @hsubramanianaks, @tejhan, @qpetraroia, @ReinierCC, @Tatsinnit for contributions, testing and reviews.
VSIX for quick test for anyone keen, please:
[vscode-aks-tools-1.5.4-test.vsix.zip](https://github.com/user-attachments/files/18132264/vscode-aks-tools-1.5.4-test.vsix.zip)

Publish release 1.5.4

---

package-lock.json
package.json
src/commands/aksFleet/aksFleetManager.ts
src/panels/CreateFleetPanel.ts

This is the initial pull request, implementing the API call for fleet creation and the callback function triggered by the user’s right-click on the ‘Create Fleet’ button.
The entry point (the ‘Create Fleet’ button) for this function is not yet available in the UI. This ensures that users will not encounter features still under development, enabling seamless and incremental integrations.

Adding API calls to create a Fleet

---

eslint.config.mjs
package-lock.json
package.json
webview-ui/eslint.config.mjs
webview-ui/package-lock.json
webview-ui/package.json

Possible fix for https://github.com/Azure/vscode-aks-tools/pull/1132 
Opening this PR to check if all checks will pass. 👮‍♂️ 
very early checkin, but we should also check after removing `cjs` files as those must be redundant now.
* auto generated files / migration: https://eslint.org/docs/latest/use/configure/migration-guide#migrate-your-config-file 
thanks. and ❤️  cc: @tejhan , @ReinierCC , @hsubramanianaks

Fix the upgrade for eslint 9.17.0.

---

.github/workflows/format-check.yml

This PR take care of this work item: https://github.com/Azure/vscode-aks-tools/issues/1162 
For now its for thought share for folks.
thanks heaps.

Add prettier format check.

---

src/commands/utils/arm.ts
src/panels/CreateFleetPanel.ts
src/webview-contract/webviewDefinitions/createFleet.ts
src/webview-contract/webviewTypes.ts
webview-ui/src/main.tsx
webview-ui/src/manualTest/main.tsx

This pull request introduces the basic panel implementation and required webview definitions for creating fleets in the VSCode extension.
1. **Added Fleet Management Capabilities**:
- Introduced `ContainerServiceFleetClient` to manage AKS fleets.
- Implemented `getAksFleetClient` function in `arm.ts` to create a fleet client.
- Added `CreateFleetPanel` and `CreateFleetDataProvider` classes in `CreateFleetPanel.ts` for handling fleet creation UI and logic.
2. **New Webview Definitions**:
- Created `createFleet.ts` under `webviewDefinitions` to define interfaces and message types related to fleet creation.
- Updated `webviewTypes.ts` to include `CreateFleetDefinition`.
3. **UI Enhancements**:
- Added placeholder for `createFleet` in `main.tsx` and `manualTest/main.tsx` to ensure compilation …

Create Fleet: panel implementation

---

src/commands/aksFleet/aksFleetManager.ts
src/extension.ts
src/panels/CreateFleetPanel.ts
webview-ui/src/CreateFleet/CreateFleet.tsx
webview-ui/src/CreateFleet/CreateFleetInput.tsx
webview-ui/src/CreateFleet/helpers/state.ts
webview-ui/src/main.tsx

This pull request completes the full cycle of creating a fleet. Starting from right-clicking on the subscription, then loading the front-end UI after clicking "Create Fleet," prompting the user to enter inputs, validating the inputs, and finally creating the fleet which is visible in the Azure portal.
- **CreateFleet.tsx**: The front-end UI for creating a fleet, which changes based on the current state of creating a fleet. For example, displaying a "Loading" message while fetching the existing resource groups and available locations, and calling the `CreateFleetInput` to show the input form for the user to enter the fleet name, resource group, and location.
- **CreateFleetInput.tsx**: The input form that will be displayed when the state is in `CollectingInput`. It allows the user to input …

Create Fleet: Full Cycle Completed

---

src/commands/devhub/aksAutomatedDeployments.ts
src/commands/utils/clusters.ts
src/panels/DevHubAutoDeployPanel.ts
src/webview-contract/webviewDefinitions/automatedDeployments.ts
webview-ui/src/AutomatedDeployments/state.ts
webview-ui/src/manualTest/automatedDeploymentsTests.tsx

Let me know if you have any feedback or questions!
Automated Deployments Page still NOT available to user.

Get Namespaces & Create Namespace Functionality [Backend]

---

src/panels/KaitoPanel.ts
webview-ui/src/Kaito/Kaito.module.css
webview-ui/src/Kaito/Kaito.tsx

This PR handles attempted installation of KAITO on automatic clusters. 
Context : Due to nrg lockdown & deny permissions of Automatic cluster, we are unable to create federated credentials in the node resource group. This is necessary for proper KAITO installation & due to the Automatic cluster SKU configuration, we are unable to change access / permissions to allow for such. Thus, I've added safeguards to prevent failed install on auto clusters alongside a message to the user. 
Additionally, there have been some additions to the KAITO installation logic to terminate installation when errors do occur (were some cases where error would be caught but installation would continue). Also added conditional render to display error messages for failed installations. 
.vsix for testing -> …

Automatic Cluster handling for KAITO installation

---

webview-ui/src/Kaito/Kaito.tsx
webview-ui/src/KaitoManage/KaitoManage.tsx
webview-ui/src/KaitoModels/KaitoModels.tsx
webview-ui/src/KaitoTest/KaitoTest.tsx
webview-ui/src/main.css

This PR serves as a start point for the eventual migration away from the @vscode/webview-ui-toolkit/react package.
**Background** 
As mentioned in issue #1207 , the @vscode/webview-ui-toolkit has recently been deprecated & will no longer be maintained. 
There were 2 popular alternatives specializing in vscode styled components, but upon testing them, both the <a href= https://github.com/vscode-elements/elements >Vscode Elements Package</a> and the <a href= https://github.com/estruyf/vscruis >Vscode React UI Package</a> have peer dependencies of react version ^18 || ^17. Neither have been updated to work with v19 as of yet, and it doesn't seem that there are any plans to do so in the immediate future. 
We have a couple packages relying on v19 of react, most notably the fontawesome icons …

Beginning migration away from @vscode/webview-ui-toolkit/react package. 

---

.prettierrc
package-lock.json
package.json

**Changes**
This PR has a slight modification to the .prettierrc file, and a version bump for prettier.
Related Issue: https://github.com/Azure/vscode-aks-tools/issues/1162

Small update to .prettierrc file & version bump

---

src/commands/devhub/aksAutomatedDeployments.ts
src/extension.ts
src/uriHandler.ts

To leverage DevHub's callback abilities I registered callback URI inside the extension.
This is a unique uri that only the vscode extension can utilize: "vscode://ms-kubernetes-tools.vscode-aks-tools/callback".
Once the user provides goes through OATH, DevHub will redirect back to the VScode extension alerting the user that the authentication was successful or it will timeout.
Currently, there's a small edge case in where if the user revokes authorization to DevHub and quickly tries to login in again they are met with an invalid state error. 
' {"error":{"code":"400", "message":"invalid state parameter", "details":[]}} '
I believe this issue might be from the DevHub side temporarily caching the state, but the state has changed.
Still the Automated Deployments command is not available to …

Proper Devhub Callback Auth

---

src/commands/utils/clusterfilter.ts
src/commands/utils/config.ts

Hiya all, ❤️ Thank you as always! The previous implementation had redundant reassignment of `filters`, multiple checks for the same condition, and slightly convoluted logic. This refactor makes the function more intuitive and performant while preserving its intended functionality.  
I think we can do this much better with fleet type filtering as well. But for the next release opening this for thoughts. 
As a key sidetone the reason currently `mergeFilter` is needed is because the tree fire event refreshes the whole node tree, we should avoid it. This kind of fixes #1223 
Rest here is the VSIX for quick spin as well please: 
[vscode-aks-tools-1.5.5-clusterfilterfix.vsix.zip](https://github.com/user-attachments/files/18777089/vscode-aks-tools-1.5.5-clusterfilterfix.vsix.zip)

Fix Cluster filter default behaviour

---

CHANGELOG.md
package-lock.json
package.json

This PR is for the release `1.6.0`, please see the details below. For all folks to take a look and we can do the release early next week.
* [Backend] ACR Creation, App Registration Creation & Role Privileges (#1238)
* Fix Cluster filter default behaviour (#1240)
* Showing Fleets in the Treeview (#1237)
* Proper Devhub Callback Auth (#1228)
* Removing unused KAITO functions & variables (#1226)
* Small addition to prettierrc & version bump (#1225)
* Created vscode themed styling to replace several webview-ui-toolkit elements (#1222)
* Added automatic cluster creation safeguards & feedback section for failed kaito installations (#1209)
* Update kubectl generation RAG endpoint (#1221)
* Create Fleet: UX Enhancement and Webview Testing (#1194)
* Feature: Add Cluster Filtering in AKS VS Code …

Publish release 1.6.0

---

src/tree/subscriptionTreeItem.ts

This PR resolves the issue where member clusters from different subscriptions were not displayed as part of the Fleet (**case 1 was not correct**). The Treeview now accurately displays clusters and Fleets following the rules illustrated in the picture below.
**Before this PR:**
- Cluster 1 was only displayed under Subscription 1 and not under Fleet 1 in Subscription 2.
**With this PR:**
- Cluster 1 is now displayed under both Subscription 1 and Fleet 1 in Subscription 2.
**What is the issue?**
Previously, the cluster filter applied to all member clusters within a Fleet, regardless of their subscription. However, the cluster filter only includes clusters within the current subscription. As a result, member clusters from other subscriptions were always filtered out, preventing users from …

Treeview bug fix: showing members from different subscriptions

---

webview-ui/src/ClusterProperties/AgentPoolDisplay.tsx
webview-ui/src/ClusterProperties/ClusterDisplay.tsx
webview-ui/src/ClusterProperties/ClusterDisplayToolTip.tsx
webview-ui/src/CreateCluster/CreateCluster.tsx
webview-ui/src/CreateCluster/CreateClusterInput.tsx
webview-ui/src/CreateCluster/CreateResourceGroup.tsx
webview-ui/src/CreateCluster/Success.tsx
webview-ui/src/CreateFleet/CreateFleet.tsx
webview-ui/src/CreateFleet/CreateFleetInput.tsx
webview-ui/src/CreateFleet/CreateFleetModeInput.tsx
webview-ui/src/main.css

This PR specifically removes elements from the Cluster Create, Fleet Create, and Cluster Properties commands.
**.vsix for testing:** [vscode-aks-tools-1.6.0-deprecate1.vsix.zip](https://github.com/user-attachments/files/18893405/vscode-aks-tools-1.6.0-deprecate1.vsix.zip)
This is broken up as part of incremental PR's to make review & testing smoother.
For future reference:
- .secondary-button replaces VSCodeButton's appearance="secondary"
- .icon-button replaces VSCodeButton's appearance="icon"
- input[type="text"] replaces VSCodeTextInput
- input[type="checkbox"] replaces VSCodeCheckbox
- input[type="radio"] replaces VSCodeRadio
- Default "< hr >" element now has identical styling to VSCodeDivider
-  Default "< a >" element also has identical styling to VSCodeLink

[Webview UI toolkit deprecation] Cluster & fleet create, cluster properties component removal

---

package.json
webview-ui/src/InspektorGadget/Overview.tsx

Hiya, following fix is for a bug where `Deploy` button does not appear at-all for the first time and one way to enable that is via manual `kubectl` page deploy. 
* This PR also updates the binary version for inspector gadget tool.
The issue was that for the `server version` if there is no version available the string returns is `not available`
**Fix**
This PR now adds the `semver` version check, this is better than regex IMHO because it does strict parsing, battle testes and no need to craft regex.
Thank heaps and gentle fyi to ❤️  @tejhan, @ReinierCC , @bosesuneha and @davidgamero + @qpetraroia
**VSIX Package:**
[vscode-aks-tools-1.6.0-IG-Deploy-fix.vsix.zip](https://github.com/user-attachments/files/19032211/vscode-aks-tools-1.6.0-IG-Deploy-fix.vsix.zip)

Fix: Deploy button not appearing.

---

src/panels/TcpDumpPanel.ts

Slight bug observed where if a user escapes the file selection menu after clicking the button to download a TCP dump capture, the button stays stuck in the disabled downloading state.
This PR adds an error response to correct for that.
(To reproduce, select Troubleshoot Network Health > Collect TCP Dumps, select a node, start & stop a capture, then click the download button that appears next to completed capture item)
.vsix: [vscode-aks-tools-1.6.1-tcpfix.vsix.zip](https://github.com/user-attachments/files/19071081/vscode-aks-tools-1.6.1-tcpfix.vsix.zip)

TCP Dump Bug Fix

---

webview-ui/src/AttachAcrToCluster/AttachAcrToCluster.tsx
webview-ui/src/AutomatedDeployments/AutomatedDeployments.tsx
webview-ui/src/Draft/Draft.module.css
webview-ui/src/Draft/DraftDeployment/DraftDeployment.tsx
webview-ui/src/Draft/DraftDockerfile/DraftDockerfile.tsx
webview-ui/src/Draft/DraftWorkflow/DraftWorkflow.tsx
webview-ui/src/components/InlineAction.tsx
webview-ui/src/components/TextWithDropdown.module.css
webview-ui/src/components/TextWithDropdown.tsx
webview-ui/src/main.css
webview-ui/src/manualTest/components/FilePicker.module.css
webview-ui/src/manualTest/components/FilePicker.tsx

This PR specifically removes elements from the AttachAcrToCluster & DraftDeployment/Dockerfile/Workflow commands.
**.vsix for testing:** [vscode-aks-tools-1.6.0-dep3-2.vsix.zip](https://github.com/user-attachments/files/19069996/vscode-aks-tools-1.6.0-dep3-2.vsix.zip)
This is broken up as part of incremental PR's to make review & testing smoother.
For future reference:
- .secondary-button replaces VSCodeButton's appearance="secondary"
- .icon-button replaces VSCodeButton's appearance="icon"
- input[type="text"] replaces VSCodeTextInput
- input[type="checkbox"] replaces VSCodeCheckbox
- input[type="radio"] replaces VSCodeRadio
- Default "< hr >" element now has identical styling to VSCodeDivider
-  Default "< a >" element also has identical styling to VSCodeLink

[Webview UI toolkit deprecation] AttachAcrToCluster, DraftDeployment/Dockerfile/Workflow Panel component removal

---

webview-ui/src/InspektorGadget/InspektorGadget.module.css
webview-ui/src/InspektorGadget/InspektorGadget.tsx
webview-ui/src/InspektorGadget/NewTraceDialog.tsx
webview-ui/src/InspektorGadget/Overview.tsx
webview-ui/src/InspektorGadget/ResourceSelector.tsx
webview-ui/src/InspektorGadget/TraceItemSortSelector.tsx
webview-ui/src/InspektorGadget/Traces.tsx
webview-ui/src/RetinaCapture/DeleteNodeExplorerDialog.tsx
webview-ui/src/RetinaCapture/RetinaCapture.tsx
webview-ui/src/TCPDump/CaptureFilters.tsx
webview-ui/src/TCPDump/TcpDump.module.css
webview-ui/src/TCPDump/TcpDump.tsx
webview-ui/src/main.css

This PR specifically removes elements from the  Inspektor Gadget, Retina Capture & TCP Dump commands.
**.vsix for testing:** [vscode-aks-tools-1.6.0-deprecate2.vsix.zip](https://github.com/user-attachments/files/18893162/vscode-aks-tools-1.6.0-deprecate2.vsix.zip)
This is broken up as part of incremental PR's to make review & testing smoother.
For future reference:
- .secondary-button replaces VSCodeButton's appearance="secondary"
- .icon-button replaces VSCodeButton's appearance="icon"
- input[type="text"] replaces VSCodeTextInput
- input[type="checkbox"] replaces VSCodeCheckbox
- input[type="radio"] replaces VSCodeRadio
- Default "< hr >" element now has identical styling to VSCodeDivider
-  Default "< a >" element also has identical styling to VSCodeLink

[Webview UI toolkit deprecation] Inspektor Gadget, Retina Capture & TCP Dump component removal

---

src/commands/utils/clusters.ts
src/panels/ClusterPropertiesPanel.ts
src/webview-contract/webviewDefinitions/clusterProperties.ts
webview-ui/src/ClusterProperties/ClusterDisplay.tsx
webview-ui/src/ClusterProperties/ClusterDisplayToolTip.tsx
webview-ui/src/ClusterProperties/ClusterProperties.module.css
webview-ui/src/ClusterProperties/ClusterUpgrade.tsx
webview-ui/src/ClusterProperties/ConfirmationDialog.tsx
webview-ui/src/ClusterProperties/state.ts
webview-ui/src/manualTest/clusterPropertiesTests.tsx

This PR adds the requested user functionality to easily upgrade an AKS cluster's kubernetes version.
If a cluster is elegible for upgrade, a dropdown next kubernetes version will appear on the 'Cluster Properties' page.
Created two additional frontend components: `ClusterUpgrade.tsx` and `ConfirmationDialog` to handle the upgrade process.
A similar warning message from the upgrade documentation is placed on a confirmation screen displayed to the user before the upgrade process begins:
Upgrading:
I've done testing on what I believe are the possible states the upgrade but please do give the vsix additional testing (Upgrading, aborting, closing page, ...).
Latest:
[vscode-aks-tools-1.6.1-upgrade-cluster-3.vsix.zip](https://github.com/user-attachments/files/19289781/vscode-aks-tools-1.6.1-upgr …

Upgrade Cluster Kubernetes Version

---

webview-ui/src/AzureServiceOperator/AzureServiceOperator.tsx
webview-ui/src/AzureServiceOperator/Inputs.tsx
webview-ui/src/Detector/Detector.tsx
webview-ui/src/Kubectl/CommandInput.tsx
webview-ui/src/Kubectl/Kubectl.tsx
webview-ui/src/Kubectl/SaveCommandDialog.tsx
webview-ui/src/Periscope/ErrorView.tsx
webview-ui/src/Periscope/NodeActions.tsx
webview-ui/src/Periscope/Periscope.tsx
webview-ui/src/Periscope/SuccessView.tsx
webview-ui/src/main.css

This PR specifically removes elements from the AzureServiceOperator, Detectors, Kubectl, & Periscope commands.
**.vsix for testing:** [vscode-aks-tools-1.6.0-deprecation4.vsix.zip](https://github.com/user-attachments/files/18892768/vscode-aks-tools-1.6.0-deprecation4.vsix.zip)
This is broken up as part of incremental PR's to make review & testing smoother.
For future reference:
- .secondary-button replaces VSCodeButton's appearance="secondary"
- .icon-button replaces VSCodeButton's appearance="icon"
- input[type="text"] replaces VSCodeTextInput
- input[type="checkbox"] replaces VSCodeCheckbox
- input[type="radio"] replaces VSCodeRadio
- Default "< hr >" element now has identical styling to VSCodeDivider
-  Default "< a >" element also has identical styling to VSCodeLink

[Webview UI toolkit deprecation] AzureServiceOperator, Detectors, Kubectl, & Periscope Panels component removal

---

CHANGELOG.md
package-lock.json
package.json

This PR is open for the release of `1.6.3` this pr contains some amazing work like:
* Add upload logs feature for Retina Capture (#1306)
* Full replacement of VSCodeDropdown & VSCodeOption with custom react elements [Webview-UI-toolkit deprecation] (#1276)
Thank you so much to @tejhan, @bosesuneha, @ReinierCC, @davidgamero, @qpetraroia, @gambtho for contributions, testing and reviews.
VSIX to test:
[vscode-aks-tools-1.6.3-test.vsix.zip](https://github.com/user-attachments/files/19558697/vscode-aks-tools-1.6.3-test.vsix.zip)

Changes to publish 1.6.3

---

package-lock.json
package.json

This pull request reverts recent updates to the `@azure/identity` package and its dependency `open`, due to critical issues affecting Windows users. The updates introduced breaking changes that prevented Windows users from loading and viewing subscriptions or clusters within the VSCode AKS Tools extension.
- Addresses issue https://github.com/Azure/vscode-aks-tools/issues/1344
- Reverted update from `@azure/identity` from 4.8 back to 4.6
- Reverted `open` from 10.1 to 8.0 (This package specifically or (it's depdendencies)) are what introduced the breaking changes.
For a bit of detail - it seems to be that the update to  the open package included some new dependencies such as `default-browser` & `is-inside-container` package, which also came along with additional subdependencies of …

Reverting @azure/identity update to fix issues in non-wsl Windows

---

CHANGELOG.md
package-lock.json
package.json

This PR is open for the release of `1.6.4` this pr contains a key fix and detail is below:
* Reverting @azure/identity update to fix windows issue (#1345) Fix for [this bug](https://github.com/Azure/vscode-aks-tools/issues/1344)
* Update retina doc (#1334)
This release will fix : #1344 
Thank you so much to @tejhan for identitify culprit package and @bosesuneha for retina docs, also to   kejatura-dev for contributions, testing and reviews.
Thank you so much to @tejhan, @bosesuneha, @ReinierCC, @davidgamero, @qpetraroia, @gambtho for contributions, testing and reviews.
VSIX to test:
[vscode-aks-tools-1.6.4-test.vsix.zip](https://github.com/user-attachments/files/19592280/vscode-aks-tools-1.6.4-test.vsix.zip)

Publish release 1.6.4

---

webview-ui/package-lock.json
webview-ui/package.json
webview-ui/src/AzureServiceOperator/ProgressStep.tsx
webview-ui/src/ClusterProperties/ClusterProperties.module.css
webview-ui/src/ClusterProperties/ClusterProperties.tsx
webview-ui/src/ClusterProperties/ClusterUpgrade.tsx
webview-ui/src/CreateCluster/CreateCluster.tsx
webview-ui/src/CreateCluster/CreateClusterInput.tsx
webview-ui/src/CreateFleet/CreateFleet.tsx
webview-ui/src/FleetProperties/FleetProperties.tsx
webview-ui/src/InspektorGadget/InspektorGadget.module.css
webview-ui/src/InspektorGadget/InspektorGadget.tsx
webview-ui/src/InspektorGadget/NewTraceDialog.tsx
webview-ui/src/InspektorGadget/Overview.tsx
webview-ui/src/InspektorGadget/ResourceSelector.tsx
webview-ui/src/InspektorGadget/TraceOutput.tsx
webview-ui/src/Kaito/Kaito.tsx
webview-ui/src/KaitoManage/KaitoManage.tsx
webview-ui/src/KaitoModels/KaitoModels.tsx
webview-ui/src/Kubectl/CommandOutput.tsx
webview-ui/src/Periscope/SuccessView.tsx
webview-ui/src/RetinaCapture/RetinaCapture.module.css
webview-ui/src/RetinaCapture/RetinaCapture.tsx
webview-ui/src/TCPDump/TcpDump.tsx
webview-ui/src/components/ProgressRing.module.css
webview-ui/src/components/ProgressRing.tsx
webview-ui/src/components/ResourceSelector.tsx
webview-ui/src/components/TextWithDropdown.tsx

This PR finalizes the removal of the webview-ui-toolkit package and all remaining usages from the repo. 
- Removed & replaced all instances of `<VSCodePanels>`, `<VSCodePanelTab>`, `<VSCodePanelView>`, `<VSCodeDropdownButton>`, and `<VSCodeProgressRing>` elements
- Custom `<ProgressRing>` element added
- Closes out issue #1207 
(An addition to the documentation briefly describing our new options for custom element & future development will be posted in a PR shortly after this).
(I've decided to include a couple clips below to reduce testing & demonstrate functionality- mainly showing the page that was changed the most in this PR which is the InspektorGadget panel. Several other files were changed but in this PR they are mostly non-interactable elements, so there shouldn't be much worry of …

Complete removal of webview-ui-toolkit package & elements

---

docs/book/src/development/webview-development.md

This PR updates the docs with new details in the development section, outlining the available custom elements and how to use them.
With the removal of the `webview-ui-toolkit` package, all previously used components can now be replaced with either native HTML elements or our new custom alternatives. These are fully styled to match VS Code’s theming and interaction patterns, maintaining the same look and feel without the dependency.
(Submitted as a separate docs PR to be merged after the next release.)

Updating Documentation with Custom elements section

---

src/panels/RetinaCapturePanel.ts
src/panels/TcpDumpPanel.ts

Observed small issue where attempting to view downloaded files didn't work in TCP Dump & Retina panels - specifically in WSL.
It seems that the `revealFileInOS` & `open` functions both don't appear to work in WSL, so this PR implements a small fix to check for WSL environments & if detected, use the `remote-wsl.revealInExplorer` command instead.
.vsix for testing: 
[vscode-aks-tools-1.6.4-wslfolderfix.vsix.zip](https://github.com/user-attachments/files/19635675/vscode-aks-tools-1.6.4-wslfolderfix.vsix.zip)

Fix for viewing downloaded files when using WSL

---

src/commands/utils/clusterfilter.ts
src/commands/utils/config.ts
src/tree/fleetTreeItem.ts
src/tree/subscriptionTreeItem.ts

There was an issue where clusters who share names in different subscription nodes would always be selected for both subscriptions, despite removing it from the filters. It seems when matching values across subscriptions in the filter logic, we checked for name but didn't verify if the subscriptionID's matched.
(This scenario is most easily observed with fleet hub clusters, since you can very easily have clusters named "hub" across multiple subscriptions you have selected in your configuration.)
- This PR fixes the logic for that, ensuring a selected cluster from 1 sub doesn't populate the others. 
- This fixes issue #1294 
(This scenario is most easily observed with fleet hub clusters, since you can very easily have clusters named "hub" across multiple subscriptions you have selected in …

Fix for similarly named clusters showing in adjacent subscription nodes

---

CHANGELOG.md
package-lock.json
package.json

This PR is open for the release of `1.6.5` this pr contains a key fix/features/updates and detail as below:
* Update/detector upgrade scenario (#1348)
* Update retina doc (#1364)
* Fixing folder open for wsl (#1349)
* Custom elements docs (#1331)
* All webview-ui-toolkit content removed (#1330)
Thank you so much to @tejhan, @bosesuneha, @ReinierCC, @davidgamero, @qpetraroia, @gambtho for contributions, testing and reviews.
[vscode-aks-tools-1.6.5-test.vsix.zip](https://github.com/user-attachments/files/19659185/vscode-aks-tools-1.6.5-test.vsix.zip)

Publish release 1.6.5

---

src/commands/aksKaito/aksKaitoManage.ts
src/panels/KaitoManagePanel.ts

This PR introduces a fix for issue #1262. 
- When deleting a workspace in v4.4, the associated gpu node pool will also be manually deleted.
- #1262 
(This should be merged in tandem with #1318 once v4.4 is pushed to the add-on as well)

[Kaito] Fix for v4 node pool deletion issue

---

src/panels/RetinaCapturePanel.ts
src/panels/TcpDumpPanel.ts
webview-ui/src/components/CustomDropdown.module.css
webview-ui/src/main.css

It appears that some of the variable names used to access vscode global variables are no longer recognized, resulting in missing background colors & incorrect sizing. The live version hasn't been affected, and the relevant css files haven't been changed in 2+ releases, which leads me to believe it's likely that an update to VSCode caused this. When debugging the extension with the live repo code, (even code prior to 1.6.4 update), the error is observed.
This PR makes slight change for the variables to fix this.
- Added vscode prefix to identifiers that no longer work. 
This is what was observed : (missing colors & misalignments)
What it should be:
Note: This would need to be merged for next release to ensure proper input styling.
.vsix for testing: …

Updating vscode styling variables

---

CHANGELOG.md
package-lock.json
package.json

This PR is open for the release of `1.6.6` this pr contains a key KAITO fix/features/updates and detail as below:
* Automatically add newly created clusters to user's selected clusters (#1293)
* Delete gpu node pool fix (#1319)
* Updating vscode styling variables (#1350)
* KAITO v4.4 support (#1318)
Thank you so much to @tejhan for various KAITO updates! + @ReinierCC, @bosesuneha, @hungry1526 for opening bug or review contributions, testing and reviews.
[vscode-aks-tools-1.6.6-test.vsix.zip](https://github.com/user-attachments/files/19783657/vscode-aks-tools-1.6.6-test.vsix.zip)

Publish release 1.6.6

---

package.json
src/commands/aksCreateCluster/aksCreateClusterFromCopilot.ts
src/commands/aksDeployManifest/aksDeployManifest.ts
src/commands/aksOpenKubectlPanel/aksOpenKubectlPanel.ts
src/commands/utils/config.ts

This PR is to add an enable flag which can be set using `setAIRecommendationsInfoState` or get the state by using `getAIRecommendationsInfoState` for the case of enablement, one such way is like this below as sample:
Below is **just sample how this flag could be used**. cc: @tejhan and @kejatura-dev fyi please. ❤️ 
```*.ts
// Sample user prompt to enable the Azure Kubernetes Service GH CoPilot Feature
const value = await vscode.window.showInformationMessage(
`Do you want to enable the Azure Kubernetes Service GH CoPilot Feature?`,
"Yes",
"No",
);
if (value === "Yes") {
setAIRecommendationsInfoState(true);
}
if (value === "No") {
setAIRecommendationsInfoState(false);
}
```
VSIX to test:
* [vscode-aks-tools-1.6.6-copilotEnabled-test11.vsix.zip](https://github.com/user-attachments/files/20113 …

Add the enable copilot flag for gh copilot feature scenario.

---

CHANGELOG.md
package-lock.json
package.json

This PR is open for the release of `1.6.7` this pr contains following:
* Add the enable copilot flag for gh copilot feature scenario. (#1408)
Thank you so much to @tejhan, @kejatura-dev, @qpetraroia for review contributions, testing and reviews.
**VSIX for test**
* [vscode-aks-tools-1.6.7-test.vsix.zip](https://github.com/user-attachments/files/20117695/vscode-aks-tools-1.6.7-test.vsix.zip)

Publish release 1.6.7

---

.github/workflows/website.yaml

ubuntu-20.04 is fully deprecated by GitHub and can no longer be used: https://github.com/actions/runner-images/issues/11101 
Thanks.

Fix the runner break as the version is deprecated.

---

CHANGELOG.md
package-lock.json
package.json

This PR is open for the release of `1.6.8`, this PR contains following:
* Fix the preview text. (#1425)
* Fix messaging to add link to the doc. (#1411)
* Fix the runner break as the version is deprecated. (#1427)
Thank you so much to @tejhan, @kejatura-dev, @qpetraroia, @bosesuneha  for review contributions, testing and reviews.
**VSIX for test**
* [vscode-aks-tools-1.6.8-test.vsix.zip](https://github.com/user-attachments/files/20258621/vscode-aks-tools-1.6.8-test.vsix.zip)

Publish release 1.6.8

---

src/commands/aksKaito/aksKaitoManage.ts
src/commands/aksKaito/aksKaitoTest.ts
src/panels/KaitoManagePanel.ts
src/panels/KaitoModelsPanel.ts
src/panels/KaitoTestPanel.ts
src/panels/utilities/KaitoHelpers.ts
src/webview-contract/webviewDefinitions/kaitoManage.ts
src/webview-contract/webviewDefinitions/kaitoModels.ts
webview-ui/src/KaitoManage/KaitoManage.tsx
webview-ui/src/KaitoModels/KaitoModels.tsx
webview-ui/src/manualTest/kaitoManageTests.tsx

This PR enables namespace awareness amongst KAITO features, allowing workspaces deployed in non-standard namespaces to be recognized & used for deleting models, viewing them, and querying the inference server properly. 
Additionally, I've added a check for the runtime of the KAITO model, which allows selection of a proper query to the inference server based on the runtime that's being utilized. 
.vsix for testing: [Uploading vscode-aks-tools-1.6.8-runtimefix.vsix.zip…]()
Thank you to @Tatsinnit and @lyantovski or contributions & insights.

Adding namespace awareness & different runtime support for KAITO models

---

l10n/bundle.l10n.json
resources/kaitollmconfig/kaitollmconfig.json
resources/yaml/kaitoworkspace.yaml
src/commands/aksKaito/akskaitoGenerateYaml.ts
webview-ui/src/KaitoModels/KaitoModels.tsx

This PR adds the Llama3 and Qwen32b models & removes the Llama2 model which has now been deprecated in KAITO.
- Added Llama3 & Qwen32b
- Bumped apiversion from v1aplha1 to v1beta1
- Removed unused llama2 logic

Updating supported models for v0.4.6 of KAITO

---

package-lock.json
package.json
src/panels/RetinaCapturePanel.ts

This PR fixes an activation issue on Windows caused by recent versions of the `@azure/identity` package. We observed that the extension would not activate correctly when bundled with `@azure/identity` above version 4.6.
After investigating, we found that the `open` npm package was also updated alongside `@azure/identity`, and in its newer version calling `open()` on relative paths now throws an error—something it previously supported.
Because `open()` is only used in one place, I’ve replaced it with VS Code’s built-in file-reveal command and ensured the path is always resolved to its absolute form.
I’ve also bumped `@azure/identity` in this PR so we can close the Dependabot one once it’s merged.
Relevant Dependabot PRs: 
- https://github.com/Azure/vscode-aks-tools/pull/1472
- …

Safely bumping @azure/identity 4.6.0 to 4.10.1 with npm 'open' fix

---

CHANGELOG.md
package-lock.json
package.json

This PR is open for the release of `1.6.10`, this PR contains following:
* kaito GA changes (#1475)
* Resolving file path var for azure/identity upgrade fix (#1482)
* Removing deprecated & adding newly supported models (#1465)
* Add retro release for enabling. (#1447)
* Fix for workflow. (#1446)
Thank you so much to @tejhan, @lyantovski , @bosesuneha, or @davidgamero for review contributions, testing and reviews. Thank you @lyantovski for his testing work around KAITO update work. cc: @qpetraroia,  @gambtho
**VSIX for test**
[vscode-aks-tools-1.6.10-test.vsix.zip](https://github.com/user-attachments/files/20966542/vscode-aks-tools-1.6.10-test.vsix.zip)

Publish release 1.6.10

---

CHANGELOG.md
package-lock.json
package.json

This PR is open for the release of `1.6.11`, this PR contains following:
* Add new monitoring and profiling commands for Inspektor Gadget (#1512)
* Fix vsc update. (#1502)
* Fix telemetery update failure. (#1501)
* IG menu restructure: Investigate DNS and Real-time TCP Monitoring (#1466)
Thank you so much to @bosesuneha, @ReinierCC, @tejhan, @davidgamero  for contributions, testing and reviews. gentle fyi and cc: @qpetraroia , @gambtho 
Side note please: let's merge #1522 post the successful release for the documentation update. what do you all think?
**VSIX for test:**
[vscode-aks-tools-1.6.11-test.vsix.zip](https://github.com/user-attachments/files/21471899/vscode-aks-tools-1.6.11-test.vsix.zip)

Publish release 1.6.11

---

src/commands/utils/tempfile.ts
src/panels/KaitoManagePanel.ts
src/webview-contract/webviewDefinitions/kaitoManage.ts
webview-ui/src/KaitoManage/KaitoManage.tsx
webview-ui/src/KaitoManage/state.ts
webview-ui/src/manualTest/kaitoManageTests.tsx

This PR introduces a new suggested feature that allows users to easily port-forward any KAITO workspace with a single click. On the KAITO manage page, deployed models will now have an option to initiate port-forwarding. The user will be prompted to specify a port, which will automatically launch an interactive shell with the port-forward process, streamlining the workflow. 
This eliminates the need for users to manually identify the relevant service port and start port-forwarding via the CLI.
.vsix for testing here -> [vscode-aks-tools-1.6.11-port1.vsix.zip](https://github.com/user-attachments/files/21516327/vscode-aks-tools-1.6.11-port1.vsix.zip)

Added option to port-forward KAITO workspace service

---

src/commands/utils/helper/mcpServerDownloadHelper.ts

This PR fixes the download name for the aks-mcp binary for windows which is of specific format and contains extension as well.
THanks,
[vscode-aks-tools-1.6.11-windows-fix.vsix.zip](https://github.com/user-attachments/files/21555075/vscode-aks-tools-1.6.11-windows-fix.vsix.zip)

Windows binary release for win arch is specific format.

---

CHANGELOG.md
README.md
package-lock.json
package.json

This PR is open for the release of `1.6.12`, this PR contains following:
* Windows binary release for win arch is specific format. (#1526)
* Add AKS MCP Server using AKS Ext level command. (#1524)
* Added option to port-forward KAITO workspace service (#1525)
* Adding deploy workspace feature to KAITO (#1493)
* Add fix for arm-container package update. (#1521)
* Update Inspektor Gadget doc (#1522)
Thank you so much to @bosesuneha, @ReinierCC, @pavneeta, @tejhan, Julia Yin for review contributions, testing and reviews. Gentle fyi and cc: @qpetraroia , @gambtho , @pavneeta 
Side note please: let's merge #1526 before this PR to be merged.
**VSIX for test:**
* ~~Needs #1526  to be merged before I can provide the VISX~~.  
* …

Publish release 1.6.12

---

src/commands/aksRetinaCapture/aksUploadRetinaCapture.ts
src/commands/utils/azurestorage.ts

💡 This PR is to fix avoid using `DefaultAzureCredential` and user properly formed object via  `sessionProvider` .
Instead of using DefaultAzureCredential (which is designed for development/testing), the code now uses the existing VS Code authentication session through. Now it uses the `[ReadyAzureSessionProvider]` that manages the user's sign-in state.
Tested locally.
* **VSIX:**  [vscode-aks-tools-1.6.12-storage-test.vsix.zip](https://github.com/user-attachments/files/21801714/vscode-aks-tools-1.6.12-storage-test.vsix.zip)

Fix the client using sessionProvider instead of default.

---

package.json

Bump AKS MCP to v0.0.9, which includes a set of bug fixes, refer [here](https://github.com/Azure/aks-mcp/compare/v0.0.6...v0.0.9) for the changes since last version.

Bump AKS MCP to v0.0.9
