README.md
Following PR adds the `Telemetry` related disclosure to `vscode-aks-tools` extension.
Thanks heaps, cc @itowlson :)
=> Telemetry content update in Readme file.

src/commands/deployAzurePipeline/configureCicdPipeline/configurePipeline.ts
Explicitly typecasting to have a comman contract between both the extensions.
=> Typecasting resource to have a common contract

README.md, package-lock.json, package.json
This PR is to add `Build` badge to the repo for displaying CI action ~ `passing` status.
* This PR also incorporate fix of the `npm install` issue. more detailed here: https://github.com/microsoft/vscode/issues/120064 
cc: @itowlson :) thanks.
=> add build badge to the read me of repo.

resources/webviews/azureserviceoperator/azureserviceoperator.css, resources/webviews/azureserviceoperator/azureserviceoperator.html, src/commands/azureServiceOperators/helpers/azureservicehtmlhelper.ts
This PR intends to redo the recommended new ui, thanks @yunjchoi has kindly provided, screenshots below, I will get another eyes by share `vsce` with her via internal channels.
Please ignore failing build, because it will be **fixed** **under this PR** (caused by vscode old module use) : https://github.com/Azure/vscode-aks-tools/pull/63 
Thanks guys!
cc: @itowlson 
New UI Looks like following:
=> UI update for ASO (azure service operator) one click work.

package-lock.json, package.json
This PR aims to upgrade `vscode` module to avoid consistent deprecation warning for vscode: more details in here. https://github.com/Azure/vscode-aks-tools/issues/73 
Thanks,
=> vscode module updrage.

package.json
This work is to handle the untrusted workspace scenario.
Please refer to https://github.com/microsoft/vscode/issues/120251 for more details. Covers:  https://github.com/Azure/vscode-aks-tools/issues/68 
Thank you. cc: @itowlson
=> Configure to be disabled in untrusted workspaces.

package.json
This PR tries to cater need for this WI opened by vscode folks for virtual workspace: https://github.com/Azure/vscode-aks-tools/issues/69 
I played around with virtual workspace, and tried it in `vscode insider` (screenshot below) what I can see is that it will allow file exploration, look at the files and safely read the code with syntax et. al. ~~**but** will not allow debugging, which means that one of the reasons mentioned not to support is true i.e. in case of **debugging not allowed**, I see as a sample they set the support as `false`. I have not scoped the work which is required for this, (might be node_module) will be needed for remote debugging.~~
Key point:
* ~~If we see rest of things **minus** the debugging part it looks ok~~ .
* **Update** Clarification, after discussion …
=> Support virtual workspace.

CHANGELOG.md, package.json
Publishing version 0.0.11 thanks and cc @itowlson ☕️ ❤️ 🙏
=> Publish 0.0.11

package-lock.json, tsconfig.json
This PR is open to cater a fix for development time only issue `asyniterator` error which is detailed more here: https://stackoverflow.com/questions/43694281/ts2318-cannot-find-global-type-asynciterableiterator-async-generator/43694282 
the behaviour appears after successful `nom install` and `nom run webpack` and when dev will open the code in `vscode` and hit `f5` its then we see some error like this: 
Thanks,
^Tats
cc: @itowlson, @squillace or @lstocchi - for quick reference and if it looks good.
=> fix for the runtime node_module asynciterator error.

resources/webviews/periscope/periscope.html
Thank you @davefellows for this, I have fixed this messaging and please take a look, we can do one release of this sometime this week as well.
Thank you 🙏☕️❤️
=> Update periscope messaging for clarity.

CHANGELOG.md, package.json
Publishing version 0.0.12 thanks and cc @rzhang628 ☕️
=> Publish 0.0.12

CHANGELOG.md, package.json
Publishing version 0.0.13 thanks and approval for release please  cc: @gambtho, @peterbom, @rzhang628 ☕️🙏
=> Publish 0.0.13

package.json, src/commands/aksIdentitySecurity/aksIdentitySecurity.ts, src/extension.ts
This is the PR for identity and security detector, things seems to be working out of box with new changes, here is the screenshot and this PR is ready for review.
Thanks, @rzhang628 and @peterbom ❤️☕️🙏
=> Integrating Identity and security detector.

package-lock.json, resources/yaml/azureoperatorsettings.yaml, src/commands/azureServiceOperators/helpers/azureservicehelper.ts, src/commands/azureServiceOperators/helpers/azureservicehtmlhelper.ts, src/commands/azureServiceOperators/installAzureServiceOperator.ts, src/commands/azureServiceOperators/ui/azureservicebrowser.ts
This PR is to update the new ASO (Azure Service Operator) release V2 mentioned here: https://azure.github.io/azure-service-operator/ 
Essentially, old ASO v1 is deprecated and latest update is published in their official repo.
Thanks heaps, cc: @peterbom & @rzhang628  for review please ❤️☕️🙏
=> Feature upgrade - Adapt ASO v2

package-lock.json, package.json, resources/webviews/common/detector.html, src/commands/aksKnownIssuesAvailabilityPerformance/aksKnownIssuesAvailabilityPerformance.ts, src/commands/utils/webviews.ts, src/extension.ts
This PR is written with an intent of enabling last left out portal parity diagnostics detector into vscode extension.
This PR also fixes all the open vulnerabilities which was fixed using `npm audit` tool. cc: @peterbom and @rzhang628 Thanks heaps. 🙏☕️❤️
* Currently there is a `test` string coming as `description` the best solution will be to get it removed from the detector otherwise I can remove reading that field in vscode.
Thanks,
=> Integrate known issue, availability and performance diagnostics.

src/commands/azureServiceOperators/ui/azureservicebrowser.ts
Fixes the `grep` issues in `windows` machine with **No** `grep`.
Thanks, cc: @peterbom and @rzhang628 
^Tats
=> Remove Grep and use code for filter for azure.com alias.

package-lock.json, package.json, resources/webviews/aksclusterproperties/clusterproperties.html, src/commands/aksClusterProperties/aksClusterProperties.ts, src/commands/utils/clusters.ts, src/extension.ts
This specific PR adds the feature enable the fetching of key property especially the `provisioningState` of cluster as long as information for `agentPool`. cc: @peterbom and @rzhang628 ❤️🙏☕️ Thanks
=> Show cluster property feature.

CHANGELOG.md, package-lock.json, package.json
Publishing version `1.2.0` thanks and approval for release please cc: @peterbom, @rzhang628, ☕️ ❤️🙏 Thank you so much.
=> publish 1.2.0.

package-lock.json, package.json
This PR is to keep the vscode engine value updated. cc: @peterbom for review. I built and tested some feature with this change and things look good. Thanks.
=> update vscode engine.

package-lock.json, package.json, src/azure-api-utils.ts, src/commands/aksBestPractices/aksBestPractices.ts, src/commands/aksCRUDDiagnostics/aksCRUDDiagnostics.ts, src/commands/aksClusterProperties/aksClusterProperties.ts, src/commands/aksCreateClusterNavToAzurePortal/aksCreateClusterNavToAzurePortal.ts, src/commands/aksIdentitySecurity/aksIdentitySecurity.ts, src/commands/aksKnownIssuesAvailabilityPerformance/aksKnownIssuesAvailabilityPerformance.ts, src/commands/aksNavToPortal/aksNavToPortal.ts, src/commands/aksNodeHealth/aksNodeHealth.ts, src/commands/aksStarterWorkflow/configureStarterWorkflow.ts, src/commands/azureServiceOperators/installAzureServiceOperator.ts, src/commands/networkAndConnectivityDiagnostics/networkAndConnectivityDiagnostics.ts, src/commands/periscope/helpers/periscopehelper.ts, src/commands/periscope/periscope.ts, src/commands/selectSubscriptions.ts, src/commands/utils/clusters.ts, src/commands/utils/detectors.ts, src/extension.ts, src/tree/aksClusterTreeItem.ts, src/tree/azureAccountTreeItem.ts, src/tree/subscriptionTreeItem.ts, tsconfig.json, tslint.json, webpack.config.js
Hiya All, This PR intends to cater the update of the the deprecated `vscode-extensionui` package. https://www.npmjs.com/package/vscode-azureextensionui 
Thank you so much for your time and eyeballing, 
* Please note: I have tested locally and all functionalities are retained I will involve internally few folks to kindly test it as well.
Further there is a a **know issue** past web packing for the `core-tracing` which is well documented here: https://github.com/Azure/azure-sdk-for-js/issues/21745 hence the tsconfig changes.
Thanks heaps, cc: @rzhang628 , @gambtho , @peterbom , @itowlson , @philliphoff  and @squillace ❤️🙏☕️
=> Update deprecated vscode-extensionui package.

CHANGELOG.md, README.md, package-lock.json, package.json
We need this urgent release for the fix detailed int his extension: 
* https://github.com/Azure/vscode-aks-tools/pull/148
Thanks. cc: @peterbom
=> Publish 1.3.1.

CHANGELOG.md, README.md, package-lock.json, package.json
Publishing `version 1.4.0` thanks and approval for release please cc: @peterbom, @rzhang628, ☕️ ❤️🙏 Thank you so much. cc: @gambtho
Documentation article update PR reside here: https://github.com/microsoft/vscode-docs/pull/5510
=> Publish 1.3.2

src/azure-api-utils.ts, src/commands/aksNavToPortal/aksNavToPortal.ts, src/commands/periscope/helpers/periscopehelper.ts, src/commands/periscope/models/storage.ts, src/commands/periscope/periscope.ts, src/commands/utils/clusters.ts, src/tree/aksClusterTreeItem.ts
This PR checks for the location which determine the usgov cloud and then we handle the `endpoint` for the `ContainerServiceClient` which kind of fixes most of the command support for the Support of USGov cloud AKS cluster.
and hence fixes/enhances #152 
Thanks heaps and fyi cc: @peterbom, @gambtho , @rzhang628 
Thanks. ❤️🙏☕️
=> support usgov cloud endpoint.

CHANGELOG.md, package-lock.json, package.json
This will support the `UsGov` cloud feature now. and then we can scope other clouds as latter with proper requirement.
@peterbom and @rzhang628 + @gambtho Thank you so much and fyi.
Thanks,
^Tats
=> publish 1.3.3

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
I realised we have no issue template for this repo while I was adding the issue template for other repos, its a stock standard templates. Also will help clear information mentioning for the users. Thanks. ❤️🙏
=> Add issue template for bugs and feature.

package.json, resources/webviews/aksKubectlCommand/akskubectlcommand.html, src/commands/aksKubectlCommands/aksKubectlCommands.ts, src/extension.ts
This PR enables new feature for kubectl command cc: ❤️🙏☕️ @peterbom, @rzhang628 and @gambtho
=> Feature: Kubectl integration with vscode.

src/commands/azureServiceOperators/helpers/azureservicehelper.ts
Update ASO yaml version to latest released version.
This seems to be working with following changes, so not a major change. cc: @peterbom and @rzhang628 Thanks heaps.
=> Update ASO usage to latest.

src/commands/aksBestPractices/aksBestPractices.ts, src/commands/aksCRUDDiagnostics/aksCRUDDiagnostics.ts, src/commands/aksClusterProperties/aksClusterProperties.ts, src/commands/aksIdentitySecurity/aksIdentitySecurity.ts, src/commands/aksKnownIssuesAvailabilityPerformance/aksKnownIssuesAvailabilityPerformance.ts, src/commands/aksKubectlCommands/aksKubectlCommands.ts, src/commands/aksNodeHealth/aksNodeHealth.ts, src/commands/azureServiceOperators/helpers/azureservicehtmlhelper.ts, src/commands/networkAndConnectivityDiagnostics/networkAndConnectivityDiagnostics.ts, src/commands/periscope/helpers/periscopehelper.ts, src/commands/periscope/periscope.ts, src/commands/utils/webviews.ts
This PR Fixes the current CSS issue in most of web views in this extension.
The PR uses the `asWebviewUri` for correction, long terms we can make util function to do so, and adapt that into all consumers, currently doing it for enabling the fix for the bug.
* More here: https://code.visualstudio.com/api/extension-guides/webview#loading-local-content
Thank you so much in advance. ❤️🎊 ☕️ cc: @peterbom and @rzhang628
=> Fix for css custom uri to use asWebViewURI.

package-lock.json, package.json, webpack.config.js
This PR is raised to cater the vulnerability alert, most of these packages are not directly used by this extension but as a good practice its probably good to keep this inline.
Kind fyi cc: to @peterbom, @rzhang628 ❤️☕️🙏 + fyi @gambtho 
We probably should do a thorough functional test with `vsix ` for this. thanks heaps
Thanks,
=> Vulnerability fix.

CHANGELOG.md, package-lock.json, package.json
Publishing version `1.3.7` with AAD AKS cluster support and new network detector enablement feature. Thanks heaps and cc: @peterbom, @squillace and @rzhang628 + @gambtho ❤️🙏
Thanks,
^Tats
=> Publish 1.3.7

README.md
removing because marketplace threw an error:
cc: @peterbom
``` 
Error processing 'ms-kubernetes-tools.vscode-aks-tools' SVG reference in file '/extension/README.md'. Your reference to the SVG image ‘https://vsmarketplacebadge.apphb.com/version-short/ms-kubernetes-tools.vscode-aks-tools.svg’ is not supported. Please see https://aka.ms/vsmarketplace_badge for more details.
```
=> remove svg because marketplace has error

CHANGELOG.md, package-lock.json, package.json
Publishing version `1.3.9` needed to abandon 1.3.8 due to SVG marketplace errors, in this release we  with add 2 new features, some updates and ASO feature update as described below. Thanks heaps and cc: @peterbom and @rzhang628 (For testing)  ❤️🙏🎊🥷
Following feature are going out with this release:
* Managed Operations menu:
* Enable Delete cluster : https://github.com/Azure/vscode-aks-tools/pull/180
* Rotate Certificate: https://github.com/Azure/vscode-aks-tools/pull/182
* ASO Support for Kind cluster: https://github.com/Azure/vscode-aks-tools/pull/181
* Update for vscode engine: https://github.com/Azure/vscode-aks-tools/pull/179 
Thanks,
^Tats
=> Publish 1.3.9

package.json, src/commands/aksInspektorGadget/aksInspektorGadget.ts
This PR addresses all comments/suggestions I added to PR https://github.com/Azure/vscode-aks-tools/pull/190. See commit messages for further details.
cc @Tatsinnit
=> aksInspektorGadget: Some renaming to avoid confusions

package.json
=> Fix spelling of "snapshot" in menus

package.json
This PR updates the Kubelogin latest version which also contains improvement in the slowness bug which was reported recently. 
* https://github.com/Azure/kubelogin/releases/tag/v0.0.31 
Thanks heaps, @peterbom + @gambtho + @qpetraroia
=> Update Kubelogin version to use latest.

package.json, src/extension.ts
This PR is intending to introduce a very early version of AKS Walkthrough in VsCode.
Once, Mark done, user can reaches these by `shift + cmd + p` and using `welcome: walkthrough` as selection to go through list of walkthroughs available.
The mov below might be able to emphasise on the behaviour.
This will be a great fyi to many users who wonder about the list of features this extension provide which we have documented well in gh docs but its outside the vscode experience, hence bridging that gap.
Thank you so much in advance. ❤️🙏☕️
https://github.com/Azure/vscode-aks-tools/assets/6233295/564b6891-4f69-405d-bb3b-44d78eb3e423
=> Feature welcome workflow

.github/workflows/build.yml, .github/workflows/chatgpt-review.yml, .github/workflows/website.yaml
This PR is final part of #232 for renaming default branch to `main` form `master`.
Thank you and cc: @peterbom and @gambtho ❤️🙏
=> Default branch is now main.

package.json, src/extension.ts
This PR fixes #236 thank you so much all, cc: @qpetraroia and @peterbom 
As you can see, it was common `id` which was getting over written, also the media tag is not correct.
Thanks heaps.
=> Fix comon id issue.

src/panels/CreateClusterPanel.ts
Removing the unused method _handleCreateClusterSuccess.
=> remove the unused method.

src/panels/CreateClusterPanel.ts, webview-ui/src/CreateCluster/CreateClusterInput.tsx
Fix validation. cc: @peterbom, @hsubramanianaks and @qpetraroia thanks guys.
=> regex fix for validation.

webview-ui/package-lock.json, webview-ui/package.json, webview-ui/src/Detector/renderers/common.tsx, webview-ui/src/main.tsx, webview-ui/src/manualTest/main.tsx
=> Remove deprecated React function call and update `webview-ui` dependencies

package.json, src/commands/periscope/models/DraftConfig.ts, src/commands/utils/config.ts, src/commands/utils/helper/binaryDownloadHelper.ts, src/commands/utils/helper/draftBinaryDownload.ts, src/commands/utils/helper/kubectlGadgetDownload.ts, src/commands/utils/helper/kubeloginDownload.ts
This PR is the initial work for the Download Draft via AKS extension.
More direct and to the usual download folder hierarchy. Thanks heaps. ❤️❤️
=> Download Draft Binaries PR.

.github/workflows/build.yml, .github/workflows/publish.yml, package-lock.json, package.json, src/tests/runTests.ts
Hoping this should fix the [Windows build error](https://github.com/Azure/vscode-aks-tools/actions/runs/6725849825/job/18281444810).
Tests ran fine for me locally with this change.
=> Update to newer test package

src/panels/TcpDumpPanel.ts
Detail for this fix reside #296 thanks cc: @peterbom for fyi please.
=> fix the filePath as empty issue.

package-lock.json, package.json
=> fix vscode

package-lock.json, package.json, src/commands/utils/azureAccount.ts
This PR is to take care of #352  and the related changes, kind fyi to @peterbom to please test these changes for me <3 
so these changes look good, I have built on my machine and all is looking fine, the sub and other tree are not affected.
Thank you.
=> Update arm-authorization related changes.

package.json, src/commands/aksEraserTool/erasertool.ts, src/extension.ts
This PR is to support the `automatically cleaning image` scenario: https://eraser-dev.github.io/eraser/docs/quick-start#automatically-cleaning-images 
https://eraser-dev.github.io/eraser/docs/installation 
❤️☕️🙏
Basic working here.
=> Add EraserTool deploy for cluster.

README.md
Thank you, and that well spent couple of hours, for this, we will get there soon **but** 97% is good I guess.
fyi and cc ❤️☕️ @peterbom
=> Add bestpractices progress badge.

.github/workflows/codeql-analysis.yml
Enable CodeQL for this repo.
* ❤️☕️🙏 🚀Thanks fyi and cc: @peterbom, here is the test run agains my fork repo: https://github.com/Tatsinnit/vscode-aks-tools/actions/runs/7565567641/job/20601535529 
* This will also increase the SSAT rating of this repo.
=> Add codeql analysis for repo.

.github/dependabot.yml
This PR is specifically takes care of this comment, https://github.com/Azure/vscode-aks-tools/pull/452#discussion_r1468949892
Which is that line-7 to 10 already takes care of this case, its just interval is is `once weekly`. Thanks & fyi ->  #peterbom 
Thanks heaps all.
=> Remove duplcate lines.

package.json
This specific PR caters #524 chelatest version of Inspector gadget from gh is `v0.25.1` hence using that. I have tested this and things are all behaving as normal.
https://github.com/inspektor-gadget/inspektor-gadget/releases
Thanks heaps, cc: @peterbom ☕️🥷
=> Upgrade the inspektor gadget to latest stable version.

.github/workflows/publish.yml, .github/workflows/website.yaml
This PR is specifically for some quality update, this PR contains changes which involve more narrow down permission model for content write where it is needed.
* Hence removed  the goal write from one workflow and for the other one, decentralised the single job into 2 and created the needs flag to handle the dependency. (This needs to be tested which I plan. from my fork sometime today)
* Opening for the wider eyes et. al. - @peterbom , @sprab , or fyi: @qpetraroia , @hsubramanianaks and @gambtho 
* Test run in my fork : https://github.com/Tatsinnit/vscode-aks-tools/actions/runs/8387160458 
❤️☕️🙏💡🥷
Thanks heaps,
^Tats
=> Quality update: Update/workflow gh!!

CONTRIBUTING.md
More details for admin/maintainers of repo here: https://github.com/Azure/vscode-aks-tools/community 
fyi: @sprab + @peterbom ☕️🙏 thanks heaps.
=> Add Contributing standard for community standard at roots folder.

package-lock.json, package.json
This PR fixes #674 , thanks heaps.
=> Fix bump vscode 1.89 update.

.github/workflows/restrict-pr-size.yml
This PR introduces the limit to the number of line to restricted and generously 1200 lines for now.
Thanks all.
From a sample run:
=> Initial commit for PR Size Check.

package-lock.json, package.json
This PR fixes #746 issue. thank you
=> Update vscode version.

src/auth/README.md, src/commands/draft/README.md
Adds `README.md` files to help new developers understand the design behind (and possible future direction of) the recent authentication and Draft work.
=> Add developer-focused discussion of authentication and Draft work

package-lock.json, package.json
This PR fixes the #794 .
Thanks heaps and cc: @hsubramanianaks and @qpetraroia ❤️ 🙏
=> Update vscode version and engine.

webview-ui/src/ClusterProperties/ClusterDisplayToolTip.tsx, webview-ui/src/ClusterProperties/ClusterProperties.module.css
This PR is to add border for UX to look good. Thanks to @Tatsinnit.
=> U/X add border for the row.

package-lock.json, package.json
=> Fix the vscode version with engine.

package.json, src/commands/detectors/detectors.ts, src/commands/utils/detectors.ts, src/extension.ts, webview-ui/src/Periscope/Periscope.tsx
This PR resolves #872 
- Fixed bug when running `AKS Diagnostics > Known Issues, Availability and Performance`
- Added storage diagnostics
- Updated periscope information link
- Closes #872
=> AKS diagnostic bug resolved & storage diagnostic added

package-lock.json, package.json
Fixes #909 - thanks!! @hsubramanianaks , @tejhan , @ReinierCC please. <3
=> update the engine with package.

.github/workflows/build.yml
This disables few things which we have never used and unwanted telemetry project. thanks.
Thank you so much guys in advance, <3 cc: @hsubramanianaks, @ReinierCC , @tejhan  & @gambtho
=> Add flags according to the need.

src/tree/azureResourceNodeContributor.ts
Created whitelist of approved azure URLs based on currently utilized URLs.
=> Proper URL Sanitization

.github/workflows/publish-v2.yml
Previous prebuilt action being utilized by the workflow was facing rate limitations. 
Tested on Local Fork:
=> Manually fetching package.json version

CHANGELOG.md, package-lock.json, package.json
This PR is for the release `1.5.1`, please see the details below. For all folks to take a look and we can do the release early next week.
* Track Version in the Extension Code, for walkthrough.
* Remove unused and unnecessary parameters for automatic cluster creation.
Thank you so much to @tejhan, @ReinierCC, @kejatura-dev, @qpetraroia, @hsubramanianaks, @joybb, @sabbour for contributions, testing and reviews.
❤️
* VSIX for quick test for anyone keen. please: [vscode-aks-tools-1.5.1-test.vsix.zip](https://github.com/user-attachments/files/17683955/vscode-aks-tools-1.5.1-test.vsix.zip)
=> Publish release 1.5.1

package-lock.json, package.json
This fixes #1058 thanks heaps. 👮 
Reason: the engine update is mandatory with the vsc update. Thanks.
=> engine and vsce package update.

src/extension.ts
Hiya all!! PR for catering a discussion here: https://github.com/Azure/vscode-aks-tools/issues/1052#issuecomment-2492569898 
* This could help resolve the every new release to have walkthrough thing now, because it could be that new release has nothing but fixes which are non superficial. Thoughts everyone please? (please feel free to add)
Thanks heaps. @joybb , @qpetraroia 
VSIX here please:   
[vscode-aks-tools-1.5.2-test-remove-automatic.vsix.zip](https://github.com/user-attachments/files/17853404/vscode-aks-tools-1.5.2-test-remove-automatic.vsix.zip)
=> Remove activation event trigger.

package-lock.json, package.json
Hiya all, this fixes: #1144 as engine needs update with vscode package.
Thanks.
=> Fix the vscode engine dependabot.

CHANGELOG.md, package-lock.json, package.json
This PR is for the release `1.5.5`, please see the details below. 
* Right Click Draft Validate.
Thank you so much to @ReinierCC, @hsubramanianaks, @tejhan, @qpetraroia, @Tatsinnit for contributions, testing and reviews.
VSIX for quick test for anyone keen, please:
[vscode-aks-tools-1.5.5-test.vsix.zip](https://github.com/user-attachments/files/18324585/vscode-aks-tools-1.5.5-test.vsix.zip)
=> Publish version 1.5.5.

docs/book/src/development/development.md
These instructions are for the `VSIX` and how to share via GitHub for our sharing reasons. 
thanks heaps, @hsubramanianaks , @ReinierCC , @tejhan and @qpetraroia ❤️
=> Add instruction for local vsix share.

README.md
This PR is addition to some docs to the main readme file for more visibility and ease.
thanks heaps.
cc and fyi: @ReinierCC , @tejhan , @hsubramanianaks and @qpetraroia
=> Add prettier badge and development link.

package-lock.json, package.json, src/extension.ts, src/panels/CreateFleetPanel.ts, src/webview-contract/webviewDefinitions/createFleet.ts, webview-ui/src/CreateFleet/CreateFleet.module.css, webview-ui/src/CreateFleet/CreateFleet.tsx, webview-ui/src/CreateFleet/CreateFleetInput.tsx, webview-ui/src/CreateFleet/CreateFleetModeInput.tsx, webview-ui/src/manualTest/createFleetTests.tsx, webview-ui/src/manualTest/main.tsx
This PR is the release version of the Create Fleet feature, with the user entry point now enabled. It adds two extra parameters for user input, completes the webview testing file for creating a fleet, and enhances the UI for a better user experience.
- **createFleetTests.tsx:** The webview testing file for creating a fleet. It uses the input file directly and makes mock responses to locally simulate a full cycle of fleet creation. To enter the "Failed" state and the "Cancelled" state, choose "thiswillfail" and "thiswillbecancelled" respectively for the location field. All other options bring the user to the "Success" state.
- **CreateFleetModeInput.tsx:** A subfile of `CreateFleetInput`, which displays the extra two input parameters: the HubClusterMode selection button and the DnsPrefix …
=> Create Fleet: UX Enhancement and Webview Testing

src/plugins/kubectlGeneration/aksDocsRag/constants.ts
update the kubectl generation aks docs RAG endpoint to new endpoint
=> update kubectl generation endpoint

src/commands/aksKaito/akskaitoGenerateYaml.ts, src/commands/utils/kaitoValidationHelpers.ts, src/panels/KaitoPanel.ts, src/webview-contract/webviewDefinitions/kaito.ts, webview-ui/src/Kaito/Kaito.tsx, webview-ui/src/Kaito/state.ts, webview-ui/src/manualTest/kaitoTests.tsx
Many of the functions & state properties for models in the Kaito program files were shifted into a different panel during development, so this PR serves to remove some of the earlier created ones that are now unused.
- Removing unused functions & variables
(Should not affect functionality, but here is .vsix for testing)
[vscode-aks-tools-1.5.5-test.vsix.zip](https://github.com/user-attachments/files/18738893/vscode-aks-tools-1.5.5-test.vsix.zip)
=> Removing unused functions & variables (Kaito)

src/panels/DevHubAutoDeployPanel.ts, src/webview-contract/webviewDefinitions/automatedDeployments.ts, webview-ui/src/AutomatedDeployments/state.ts, webview-ui/src/manualTest/automatedDeploymentsTests.tsx
Comments explain changes.
Feel free to provide any feedback or improvements!
Feature is still not available to the user.
=> [Backend] ACR Creation, App Registration Creation & Role Privileges

package.json, src/commands/aksFleetProperties/askFleetProperties.ts, src/commands/utils/fleet.ts, src/extension.ts, src/panels/CreateFleetPanel.ts, src/panels/FleetPropertiesPanel.ts, src/tree/fleetTreeItem.ts, src/webview-contract/webviewDefinitions/fleetProperties.ts, src/webview-contract/webviewTypes.ts, webview-ui/src/FleetProperties/FleetProperties.tsx, webview-ui/src/FleetProperties/state.ts, webview-ui/src/main.tsx, webview-ui/src/manualTest/main.tsx
This PR introduces the initial implementation of the “Show Fleet Properties” feature. Additionally, it refactors the “Create a Fleet” API call function for improved code organization. The WebView test is yet to be implemented.
=> Show Fleet Properties

package.json
Hiya, Lets make this to one of recent retina release seems like we have not updated this for a while. updating with this recent release: https://github.com/microsoft/retina/releases/tag/v0.0.26 
There are bunch of work we can do post this release: 
* Like blob update.
Thanks,
=> Update: Retina Binary to recent release.

CHANGELOG.md, package-lock.json, package.json
* Show Fleet Properties (#1245)
* Treeview bug fix: showing members from different subscriptions (#1254)
* [Webview UI toolkit deprecation] Cluster & fleet create, cluster properties component removal (#1258)
* Fix: Deploy button not appearing (#1277)
* Update: Retina Binary to recent release. (#1278)
* packages: Update Inspektor Gadget to v0.38.0 (#1279)
* Dependabot updates
VSIX file for testing: 
[vscode-aks-tools-1.6.1.vsix.zip](https://github.com/user-attachments/files/19061357/vscode-aks-tools-1.6.1.vsix.zip)
=> Release v1.6.1

package-lock.json, webview-ui/package-lock.json
This PR fixes this build warning.
thanks heaps, @ReinierCC , @tejhan , @qpetraroia , @bosesuneha + @davidgamero
=> Fix npm warning for build.

docs/book/src/features/retina-capture.md
Adding the specific steps associated with each screenshot for better understanding.
=> Update retina doc with steps

.github/workflows/publish-v2.yml
Reverting for potential issue with build workflow.
=> Revert Login Action

docs/book/src/features/aks-plugins-github-copilot.md
This is the addition as to how to add the flag as false for the copilot.
Thanks heaps.
=> Documentation for the copilot flag.

src/commands/aksCreateCluster/aksCreateClusterFromCopilot.ts, src/commands/aksDeployManifest/aksDeployManifest.ts, src/commands/aksOpenKubectlPanel/aksOpenKubectlPanel.ts, src/commands/utils/clusters.ts
These changes achieve this, which will be more clear and direct help for users who might find changing setting complex. ❤️
=> Fix messaging to add link to the doc.

webview-ui/src/components/CustomDropdown.tsx, webview-ui/src/components/CustomDropdownOption.tsx
This PR serves introduces the necessary ARIA roles & keyboard navigation enablement to ensure that our custom created dropdown element is fully accessible.
=> Adding ARIA roles & accessible keyboard navigation to CustomDropdown components

.github/workflows/format-check.yml
This PR will fix 2 security alerts:
* https://github.com/Azure/vscode-aks-tools/security/code-scanning/39 
* https://github.com/Azure/vscode-aks-tools/security/code-scanning/40
Thanks, and fyi @tejhan
=> Fix for catering security alerts and permissions.

package-lock.json, package.json, src/commands/utils/reporter.ts
This PR will help in fixing the #1421 which is open for a bit, and help migrating to the version above. thanks.
=> Fix telemetery update failure.

package-lock.json, package.json, src/commands/utils/azureResources.ts, src/commands/utils/fleet.ts, src/panels/FleetPropertiesPanel.ts, webview-ui/package-lock.json
This PR is intended to fix #1459 
Hiya @tejhan, gentle ping for review / test please. Thanks.
=> Update arm-containerservicefleet package and related changes.

package-lock.json, package.json
This PR fixes #1631 and associated break. thank you
Thanks and gentle fyi ❤️ cc: @tejhan, @ReinierCC , @davidgamero or @bosesuneha - @gambtho and @qpetraroia
=> Add latest VSC engine and package.
